// ═══════════════════════════════════════
// ESD v2 — Content Data (Auto-generated)
// ═══════════════════════════════════════
// FR translations: placeholders use EN text. Replace with FR before launch.

import type { Dimension, Question, Statement, Trait, TraitId, DimensionId, Band, DesignAdoptionTag } from './types'

// ── Dimensions ──
export const DIMENSIONS: Dimension[] = [
  {
    id: 'D1' as DimensionId,
    name: { en: `Decision Rights & Governance`, fr: `Decision Rights & Governance` },
    system: 'Structural',
    weight: 0.15,
    hasDesignAdoption: true,
    description: { en: `Clarity of decision ownership, consultation, escalation, and governance speed.`, fr: `Clarity of decision ownership, consultation, escalation, and governance speed.` },
  },
  {
    id: 'D2' as DimensionId,
    name: { en: `Organisational Design & Role Clarity`, fr: `Organisational Design & Role Clarity` },
    system: 'Structural',
    weight: 0.1,
    hasDesignAdoption: true,
    description: { en: `Fit between structure and strategy. Whether interfaces exist AND function.`, fr: `Fit between structure and strategy. Whether interfaces exist AND function.` },
  },
  {
    id: 'D3' as DimensionId,
    name: { en: `Coordination & Synchronisation`, fr: `Coordination & Synchronisation` },
    system: 'Structural',
    weight: 0.15,
    hasDesignAdoption: true,
    description: { en: `Accountability for coordination, predictability of cross-team working.`, fr: `Accountability for coordination, predictability of cross-team working.` },
  },
  {
    id: 'D4' as DimensionId,
    name: { en: `Goal Architecture & OKR Maturity`, fr: `Goal Architecture & OKR Maturity` },
    system: 'Structural',
    weight: 0.12,
    hasDesignAdoption: true,
    description: { en: `Goal quality, dependency management, roadmap sequencing.`, fr: `Goal quality, dependency management, roadmap sequencing.` },
  },
  {
    id: 'D5' as DimensionId,
    name: { en: `Performance Tracking & Adaptation`, fr: `Performance Tracking & Adaptation` },
    system: 'Structural',
    weight: 0.1,
    hasDesignAdoption: true,
    description: { en: `Line of sight, reporting coherence, signal detection, adaptive capacity.`, fr: `Line of sight, reporting coherence, signal detection, adaptive capacity.` },
  },
  {
    id: 'D6' as DimensionId,
    name: { en: `Leadership Alignment & Capability`, fr: `Leadership Alignment & Capability` },
    system: 'Social',
    weight: 0.18,
    hasDesignAdoption: false,
    description: { en: `Senior team cohesion, cascade, diagnostic capability, social capital, capability-strategy fit.`, fr: `Senior team cohesion, cascade, diagnostic capability, social capital, capability-strategy fit.` },
  },
  {
    id: 'D7' as DimensionId,
    name: { en: `Communication & Sensemaking`, fr: `Communication & Sensemaking` },
    system: 'Social',
    weight: 0.1,
    hasDesignAdoption: false,
    description: { en: `Strategy translation, information flow upward and lateral.`, fr: `Strategy translation, information flow upward and lateral.` },
  },
  {
    id: 'D8' as DimensionId,
    name: { en: `Commitment, Ownership & Incentives`, fr: `Commitment, Ownership & Incentives` },
    system: 'Social',
    weight: 0.1,
    hasDesignAdoption: false,
    description: { en: `Ownership depth, involvement quality, incentive alignment.`, fr: `Ownership depth, involvement quality, incentive alignment.` },
  },
]

// ── Traits ──
export const TRAITS: Trait[] = [
  {
    id: 'TRT_CA' as TraitId,
    name: { en: `Clarity of Authority`, fr: `Clarity of Authority` },
    description: { en: `How clearly ownership, accountability, and decision-making power are defined.`, fr: `How clearly ownership, accountability, and decision-making power are defined.` },
    interventionCriticalRed: { en: `Build a Decisions RACI for the top 15–20 contested decisions. Name singular accountable owners.`, fr: `Build a Decisions RACI for the top 15–20 contested decisions. Name singular accountable owners.` },
    interventionAmber: { en: `Clarify authority at the specific cross-functional interfaces most critical to the strategy.`, fr: `Clarify authority at the specific cross-functional interfaces most critical to the strategy.` },
  },
  {
    id: 'TRT_SA' as TraitId,
    name: { en: `Strategic Alignment`, fr: `Strategic Alignment` },
    description: { en: `How consistently all elements point in the same strategic direction.`, fr: `How consistently all elements point in the same strategic direction.` },
    interventionCriticalRed: { en: `Conduct a strategic alignment audit: do structure, goals, incentives, and leadership signals all point the same way? Fix contradictions.`, fr: `Conduct a strategic alignment audit: do structure, goals, incentives, and leadership signals all point the same way? Fix contradictions.` },
    interventionAmber: { en: `Identify and resolve the 2–3 most visible contradictions between strategy messaging and system signals.`, fr: `Identify and resolve the 2–3 most visible contradictions between strategy messaging and system signals.` },
  },
  {
    id: 'TRT_CI' as TraitId,
    name: { en: `Cross-boundary Integration`, fr: `Cross-boundary Integration` },
    description: { en: `Ability to work effectively across functions, teams, and business units.`, fr: `Ability to work effectively across functions, teams, and business units.` },
    interventionCriticalRed: { en: `Assign coordination owners for every critical cross-functional workstream. Design handover protocols. Create shared working rhythms.`, fr: `Assign coordination owners for every critical cross-functional workstream. Design handover protocols. Create shared working rhythms.` },
    interventionAmber: { en: `Strengthen coordination mechanisms for the highest-priority cross-functional workstreams. Address structural barriers to collaboration.`, fr: `Strengthen coordination mechanisms for the highest-priority cross-functional workstreams. Address structural barriers to collaboration.` },
  },
  {
    id: 'TRT_ED' as TraitId,
    name: { en: `Execution Discipline`, fr: `Execution Discipline` },
    description: { en: `Rigour of goal-setting, dependency management, and roadmap sequencing.`, fr: `Rigour of goal-setting, dependency management, and roadmap sequencing.` },
    interventionCriticalRed: { en: `Implement OKR quality gates, dependency mapping, and cross-team delivery planning before scaling.`, fr: `Implement OKR quality gates, dependency mapping, and cross-team delivery planning before scaling.` },
    interventionAmber: { en: `Improve goal quality through coaching and review. Extend dependency mapping to all deployment-critical workstreams.`, fr: `Improve goal quality through coaching and review. Extend dependency mapping to all deployment-critical workstreams.` },
  },
  {
    id: 'TRT_AC' as TraitId,
    name: { en: `Adaptive Capacity`, fr: `Adaptive Capacity` },
    description: { en: `Speed and effectiveness of detecting problems, learning, and adjusting course.`, fr: `Speed and effectiveness of detecting problems, learning, and adjusting course.` },
    interventionCriticalRed: { en: `Establish shorter feedback loops. Deploy leading indicators. Create safe mechanisms for surfacing problems early.`, fr: `Establish shorter feedback loops. Deploy leading indicators. Create safe mechanisms for surfacing problems early.` },
    interventionAmber: { en: `Reduce the time between problem emergence and leadership awareness. Build learning-from-failure protocols.`, fr: `Reduce the time between problem emergence and leadership awareness. Build learning-from-failure protocols.` },
  },
  {
    id: 'TRT_II' as TraitId,
    name: { en: `Information Integrity`, fr: `Information Integrity` },
    description: { en: `How freely, quickly, and honestly critical information moves.`, fr: `How freely, quickly, and honestly critical information moves.` },
    interventionCriticalRed: { en: `Create unfiltered upward communication channels. Shift from blame-oriented to system-oriented responses. Leaders must actively seek bad news.`, fr: `Create unfiltered upward communication channels. Shift from blame-oriented to system-oriented responses. Leaders must actively seek bad news.` },
    interventionAmber: { en: `Identify and address the specific barriers to honest upward communication. Improve lateral information sharing across functions.`, fr: `Identify and address the specific barriers to honest upward communication. Improve lateral information sharing across functions.` },
  },
  {
    id: 'TRT_DC' as TraitId,
    name: { en: `Diagnostic Capability`, fr: `Diagnostic Capability` },
    description: { en: `Leaders' ability to read execution challenges and match the right intervention.`, fr: `Leaders' ability to read execution challenges and match the right intervention.` },
    interventionCriticalRed: { en: `Invest in diagnostic frameworks: is this a structural, capability, motivational, or coordination problem? External facilitation for the first major challenge.`, fr: `Invest in diagnostic frameworks: is this a structural, capability, motivational, or coordination problem? External facilitation for the first major challenge.` },
    interventionAmber: { en: `Build shared language for distinguishing problem types. Create a habit of root-cause analysis before intervention selection.`, fr: `Build shared language for distinguishing problem types. Create a habit of root-cause analysis before intervention selection.` },
  },
  {
    id: 'TRT_LI' as TraitId,
    name: { en: `Leadership Influence`, fr: `Leadership Influence` },
    description: { en: `Credibility, trust, and relational capital to mobilise action beyond compliance.`, fr: `Credibility, trust, and relational capital to mobilise action beyond compliance.` },
    interventionCriticalRed: { en: `Invest in trust-based leadership development. Deploy high-credibility leaders to critical workstreams. Address credibility gaps honestly.`, fr: `Invest in trust-based leadership development. Deploy high-credibility leaders to critical workstreams. Address credibility gaps honestly.` },
    interventionAmber: { en: `Identify leaders with strongest cross-functional influence and deploy them strategically. Provide support for leaders with credibility gaps.`, fr: `Identify leaders with strongest cross-functional influence and deploy them strategically. Provide support for leaders with credibility gaps.` },
  },
  {
    id: 'TRT_CO' as TraitId,
    name: { en: `Collective Ownership`, fr: `Collective Ownership` },
    description: { en: `Depth of genuine commitment, engagement, and shared purpose.`, fr: `Depth of genuine commitment, engagement, and shared purpose.` },
    interventionCriticalRed: { en: `Move from informing to co-creating. Involve middle managers in shaping execution approach. Address scepticism from past failures directly.`, fr: `Move from informing to co-creating. Involve middle managers in shaping execution approach. Address scepticism from past failures directly.` },
    interventionAmber: { en: `Deepen involvement of the next tier of delivery leads. Complete incentive realignment across critical functions.`, fr: `Deepen involvement of the next tier of delivery leads. Complete incentive realignment across critical functions.` },
  },
  {
    id: 'TRT_CF' as TraitId,
    name: { en: `Capability-Strategy Fit`, fr: `Capability-Strategy Fit` },
    description: { en: `Match between what people can do and what this specific strategy demands.`, fr: `Match between what people can do and what this specific strategy demands.` },
    interventionCriticalRed: { en: `Conduct an honest capability-strategy fit assessment. Invest in targeted development, coaching, or recruitment where gaps are critical.`, fr: `Conduct an honest capability-strategy fit assessment. Invest in targeted development, coaching, or recruitment where gaps are critical.` },
    interventionAmber: { en: `Address the most critical capability gaps through coaching or advisory support. Accelerate development for leaders facing unfamiliar challenges.`, fr: `Address the most critical capability gaps through coaching or advisory support. Accelerate development for leaders facing unfamiliar challenges.` },
  },
]

// ── Questions ──
export const QUESTIONS: Question[] = [
  {
    id: 'Q01',
    dimensionId: 'D1' as DimensionId,
    text: { en: `How clearly defined are decision rights across the organisation — do people know who owns which decisions, who needs to be consulted, and who has final authority?`, fr: `How clearly defined are decision rights across the organisation — do people know who owns which decisions, who needs to be consulted, and who has final authority?` },
    contextPrompt: { en: `Describe a recent decision that was difficult to resolve. What made it difficult — who was involved, what was contested, and how long did it take?`, fr: `Describe a recent decision that was difficult to resolve. What made it difficult — who was involved, what was contested, and how long did it take?` },
    statements: [
      {
        id: 'S01A',
        questionId: 'Q01',
        text: { en: `When urgent decisions arise, they often bounce between people until someone senior steps in — because it's unclear who has the authority to make the call.`, fr: `When urgent decisions arise, they often bounce between people until someone senior steps in — because it's unclear who has the authority to make the call.` },
        polarity: -1 as 1 | -1,
        tag: 'Adoption' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 6, 'TRT_SA': 0, 'TRT_CI': 2, 'TRT_ED': 0, 'TRT_AC': 2, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S01B',
        questionId: 'Q01',
        text: { en: `Decision authority is well understood within each function, but at the cross-functional boundaries where the strategy needs coordination, ownership over decisions is ambiguous.`, fr: `Decision authority is well understood within each function, but at the cross-functional boundaries where the strategy needs coordination, ownership over decisions is ambiguous.` },
        polarity: -1 as 1 | -1,
        tag: 'Adoption' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 3, 'TRT_SA': 2, 'TRT_CI': 5, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S01C',
        questionId: 'Q01',
        text: { en: `A small number of senior leaders are the de facto decision-makers for almost everything — things work when they're available, but stall when they're not.`, fr: `A small number of senior leaders are the de facto decision-makers for almost everything — things work when they're available, but stall when they're not.` },
        polarity: -1 as 1 | -1,
        tag: 'Adoption' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 4, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 3, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 3, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S01D',
        questionId: 'Q01',
        text: { en: `People at middle management level generally know what they can decide on their own and escalate only when genuinely needed.`, fr: `People at middle management level generally know what they can decide on their own and escalate only when genuinely needed.` },
        polarity: 1 as 1 | -1,
        tag: 'Adoption' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 5, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 2, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 3, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S01E',
        questionId: 'Q01',
        text: { en: `There is a documented decision framework (e.g., RACI or decision matrix) that has been reviewed for the new strategy and reflects how decisions actually get made — not just how they should get made on paper.`, fr: `There is a documented decision framework (e.g., RACI or decision matrix) that has been reviewed for the new strategy and reflects how decisions actually get made — not just how they should get made on paper.` },
        polarity: 1 as 1 | -1,
        tag: 'Design' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 4, 'TRT_SA': 3, 'TRT_CI': 0, 'TRT_ED': 3, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
    ],
  },
  {
    id: 'Q02',
    dimensionId: 'D1' as DimensionId,
    text: { en: `How well does the current governance system support the speed and quality of decision-making the strategy demands?`, fr: `How well does the current governance system support the speed and quality of decision-making the strategy demands?` },
    contextPrompt: { en: `Think of a decision that should have been straightforward but wasn't. What slowed it down or caused it to be revisited?`, fr: `Think of a decision that should have been straightforward but wasn't. What slowed it down or caused it to be revisited?` },
    statements: [
      {
        id: 'S02A',
        questionId: 'Q02',
        text: { en: `Most decisions pass through multiple approval layers before anything moves — even relatively routine ones require sign-offs that slow the process significantly.`, fr: `Most decisions pass through multiple approval layers before anything moves — even relatively routine ones require sign-offs that slow the process significantly.` },
        polarity: -1 as 1 | -1,
        tag: 'Adoption' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 4, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 2, 'TRT_AC': 4, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S02B',
        questionId: 'Q02',
        text: { en: `Decisions get made at a reasonable pace, but they are frequently revisited or overridden afterward, which creates uncertainty about whether a decision is truly final.`, fr: `Decisions get made at a reasonable pace, but they are frequently revisited or overridden afterward, which creates uncertainty about whether a decision is truly final.` },
        polarity: -1 as 1 | -1,
        tag: 'Adoption' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 5, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 3, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 2, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S02C',
        questionId: 'Q02',
        text: { en: `The governance system has been designed for the new strategy, but it has not yet been tested under real operating conditions — we don't know if it will hold under pressure.`, fr: `The governance system has been designed for the new strategy, but it has not yet been tested under real operating conditions — we don't know if it will hold under pressure.` },
        polarity: -1 as 1 | -1,
        tag: 'Design' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 2, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 4, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 4 } as Record<TraitId, number>,
      },
      {
        id: 'S02D',
        questionId: 'Q02',
        text: { en: `Leaders regularly delegate decision-making to the appropriate level, and people feel empowered to act within their mandates without seeking unnecessary permission.`, fr: `Leaders regularly delegate decision-making to the appropriate level, and people feel empowered to act within their mandates without seeking unnecessary permission.` },
        polarity: 1 as 1 | -1,
        tag: 'Adoption' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 4, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 3, 'TRT_CO': 3, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S02E',
        questionId: 'Q02',
        text: { en: `Governance forums and approval processes have been explicitly reviewed and reconfigured for the new strategy's demands — legacy structures have been retired or adapted.`, fr: `Governance forums and approval processes have been explicitly reviewed and reconfigured for the new strategy's demands — legacy structures have been retired or adapted.` },
        polarity: 1 as 1 | -1,
        tag: 'Design' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 5, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 3, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 2 } as Record<TraitId, number>,
      },
    ],
  },
  {
    id: 'Q03',
    dimensionId: 'D2' as DimensionId,
    text: { en: `Does the current organisational structure create the right interfaces for the teams that need to collaborate on shared outcomes?`, fr: `Does the current organisational structure create the right interfaces for the teams that need to collaborate on shared outcomes?` },
    contextPrompt: { en: `Which two teams need to collaborate most closely under the current strategy? How well does the structure support that collaboration?`, fr: `Which two teams need to collaborate most closely under the current strategy? How well does the structure support that collaboration?` },
    statements: [
      {
        id: 'S03A',
        questionId: 'Q03',
        text: { en: `The teams that need to collaborate most closely currently sit in entirely separate parts of the organisation with no shared reporting, meetings, or natural interaction points.`, fr: `The teams that need to collaborate most closely currently sit in entirely separate parts of the organisation with no shared reporting, meetings, or natural interaction points.` },
        polarity: -1 as 1 | -1,
        tag: 'Design' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 2, 'TRT_CI': 6, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 2 } as Record<TraitId, number>,
      },
      {
        id: 'S03B',
        questionId: 'Q03',
        text: { en: `Cross-functional forums exist, but they were designed for previous priorities and may not bring the right people together for the current strategy.`, fr: `Cross-functional forums exist, but they were designed for previous priorities and may not bring the right people together for the current strategy.` },
        polarity: -1 as 1 | -1,
        tag: 'Design' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 3, 'TRT_CI': 4, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 3 } as Record<TraitId, number>,
      },
      {
        id: 'S03C',
        questionId: 'Q03',
        text: { en: `The organisation has recently restructured to create the right interfaces, but the new interfaces have not yet developed effective working relationships — the structure is right but the collaboration muscle is untested.`, fr: `The organisation has recently restructured to create the right interfaces, but the new interfaces have not yet developed effective working relationships — the structure is right but the collaboration muscle is untested.` },
        polarity: -1 as 1 | -1,
        tag: 'Adoption' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 2, 'TRT_CI': 5, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 3 } as Record<TraitId, number>,
      },
      {
        id: 'S03D',
        questionId: 'Q03',
        text: { en: `The organisation has recently restructured or realigned teams in ways that create most of the interfaces the strategy needs, and these interfaces are starting to function.`, fr: `The organisation has recently restructured or realigned teams in ways that create most of the interfaces the strategy needs, and these interfaces are starting to function.` },
        polarity: 1 as 1 | -1,
        tag: 'Both' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 4, 'TRT_CI': 4, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 2 } as Record<TraitId, number>,
      },
      {
        id: 'S03E',
        questionId: 'Q03',
        text: { en: `People have developed informal workarounds — relationships, back-channels, ad hoc meetings — to compensate for structural gaps, but these depend on specific individuals and are fragile.`, fr: `People have developed informal workarounds — relationships, back-channels, ad hoc meetings — to compensate for structural gaps, but these depend on specific individuals and are fragile.` },
        polarity: -1 as 1 | -1,
        tag: 'Adoption' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 4, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 3, 'TRT_CO': 0, 'TRT_CF': 3 } as Record<TraitId, number>,
      },
    ],
  },
  {
    id: 'Q04',
    dimensionId: 'D2' as DimensionId,
    text: { en: `How clearly defined are roles, responsibilities, and mandates — particularly at the boundaries where functions need to hand off work or make joint decisions?`, fr: `How clearly defined are roles, responsibilities, and mandates — particularly at the boundaries where functions need to hand off work or make joint decisions?` },
    contextPrompt: { en: `Describe a recent hand-off between teams. Was it clean or messy? What caused the friction?`, fr: `Describe a recent hand-off between teams. Was it clean or messy? What caused the friction?` },
    statements: [
      {
        id: 'S04A',
        questionId: 'Q04',
        text: { en: `Within functions, people generally know their role — but the moment work crosses a functional boundary, it becomes unclear who owns what, and things fall through the gaps.`, fr: `Within functions, people generally know their role — but the moment work crosses a functional boundary, it becomes unclear who owns what, and things fall through the gaps.` },
        polarity: -1 as 1 | -1,
        tag: 'Adoption' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 5, 'TRT_SA': 0, 'TRT_CI': 3, 'TRT_ED': 2, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S04B',
        questionId: 'Q04',
        text: { en: `Certain roles have been deliberately designed to sit at the intersection of functions, and these bridge roles genuinely help clarify who does what at the boundaries.`, fr: `Certain roles have been deliberately designed to sit at the intersection of functions, and these bridge roles genuinely help clarify who does what at the boundaries.` },
        polarity: 1 as 1 | -1,
        tag: 'Design' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 3, 'TRT_SA': 0, 'TRT_CI': 4, 'TRT_ED': 3, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S04C',
        questionId: 'Q04',
        text: { en: `Role descriptions exist on paper, but people's actual scope has drifted from what is documented — stated responsibilities and real responsibilities don't match.`, fr: `Role descriptions exist on paper, but people's actual scope has drifted from what is documented — stated responsibilities and real responsibilities don't match.` },
        polarity: -1 as 1 | -1,
        tag: 'Adoption' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 4, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 3, 'TRT_AC': 0, 'TRT_II': 3, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S04D',
        questionId: 'Q04',
        text: { en: `When two teams need to hand off work, there is usually a period of confusion about who picks it up, who checks quality, and who is accountable if something goes wrong.`, fr: `When two teams need to hand off work, there is usually a period of confusion about who picks it up, who checks quality, and who is accountable if something goes wrong.` },
        polarity: -1 as 1 | -1,
        tag: 'Adoption' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 4, 'TRT_SA': 0, 'TRT_CI': 4, 'TRT_ED': 2, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S04E',
        questionId: 'Q04',
        text: { en: `Leaders have recently or are currently clarifying roles and mandates in anticipation of the strategy's demands — this work is in progress but not yet complete.`, fr: `Leaders have recently or are currently clarifying roles and mandates in anticipation of the strategy's demands — this work is in progress but not yet complete.` },
        polarity: 1 as 1 | -1,
        tag: 'Design' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 3, 'TRT_SA': 4, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 3 } as Record<TraitId, number>,
      },
    ],
  },
  {
    id: 'Q05',
    dimensionId: 'D3' as DimensionId,
    text: { en: `Who explicitly owns cross-functional coordination — is there clear accountability for keeping shared work synchronised?`, fr: `Who explicitly owns cross-functional coordination — is there clear accountability for keeping shared work synchronised?` },
    contextPrompt: { en: `When two departments disagree about priorities or sequencing, how is it resolved? Who mediates?`, fr: `When two departments disagree about priorities or sequencing, how is it resolved? Who mediates?` },
    statements: [
      {
        id: 'S05A',
        questionId: 'Q05',
        text: { en: `When cross-functional work falls through the cracks, each function points to the other — nobody clearly owns the coordination space in between.`, fr: `When cross-functional work falls through the cracks, each function points to the other — nobody clearly owns the coordination space in between.` },
        polarity: -1 as 1 | -1,
        tag: 'Adoption' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 5, 'TRT_SA': 0, 'TRT_CI': 3, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 2, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S05B',
        questionId: 'Q05',
        text: { en: `Coordination happens because specific individuals take it upon themselves — it is personality-driven rather than built into how the organisation operates.`, fr: `Coordination happens because specific individuals take it upon themselves — it is personality-driven rather than built into how the organisation operates.` },
        polarity: -1 as 1 | -1,
        tag: 'Adoption' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 4, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 3, 'TRT_CO': 0, 'TRT_CF': 3 } as Record<TraitId, number>,
      },
      {
        id: 'S05C',
        questionId: 'Q05',
        text: { en: `Certain major programmes have named coordinators, but the vast majority of cross-functional work has no explicit coordination owner.`, fr: `Certain major programmes have named coordinators, but the vast majority of cross-functional work has no explicit coordination owner.` },
        polarity: -1 as 1 | -1,
        tag: 'Design' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 4, 'TRT_SA': 0, 'TRT_CI': 4, 'TRT_ED': 2, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S05D',
        questionId: 'Q05',
        text: { en: `The organisation has established clear accountability for cross-functional coordination — named owners, established rhythms, and explicit mandates for keeping shared work synchronised.`, fr: `The organisation has established clear accountability for cross-functional coordination — named owners, established rhythms, and explicit mandates for keeping shared work synchronised.` },
        polarity: 1 as 1 | -1,
        tag: 'Both' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 4, 'TRT_SA': 0, 'TRT_CI': 3, 'TRT_ED': 3, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S05E',
        questionId: 'Q05',
        text: { en: `Senior leaders assume coordination is happening because they have asked for it — but there is no mechanism to verify whether teams are actually synchronised.`, fr: `Senior leaders assume coordination is happening because they have asked for it — but there is no mechanism to verify whether teams are actually synchronised.` },
        polarity: -1 as 1 | -1,
        tag: 'Adoption' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 2, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 4, 'TRT_DC': 4, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
    ],
  },
  {
    id: 'Q06',
    dimensionId: 'D3' as DimensionId,
    text: { en: `How predictable and reliable is cross-team working — can teams plan their own work with confidence about what other teams will deliver?`, fr: `How predictable and reliable is cross-team working — can teams plan their own work with confidence about what other teams will deliver?` },
    contextPrompt: { en: `Have you experienced a situation where a project was delayed because another team had different assumptions? What happened?`, fr: `Have you experienced a situation where a project was delayed because another team had different assumptions? What happened?` },
    statements: [
      {
        id: 'S06A',
        questionId: 'Q06',
        text: { en: `Teams regularly discover mid-project that another team has different assumptions about timelines, deliverables, or quality standards.`, fr: `Teams regularly discover mid-project that another team has different assumptions about timelines, deliverables, or quality standards.` },
        polarity: -1 as 1 | -1,
        tag: 'Adoption' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 4, 'TRT_ED': 3, 'TRT_AC': 0, 'TRT_II': 3, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S06B',
        questionId: 'Q06',
        text: { en: `Teams operate on incompatible planning rhythms, making it structurally difficult to synchronise work even when people want to.`, fr: `Teams operate on incompatible planning rhythms, making it structurally difficult to synchronise work even when people want to.` },
        polarity: -1 as 1 | -1,
        tag: 'Design' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 2, 'TRT_CI': 4, 'TRT_ED': 4, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S06C',
        questionId: 'Q06',
        text: { en: `There are well-established shared processes for how teams work together — including common definitions of 'done', agreed handoff points, and compatible planning cycles.`, fr: `There are well-established shared processes for how teams work together — including common definitions of 'done', agreed handoff points, and compatible planning cycles.` },
        polarity: 1 as 1 | -1,
        tag: 'Both' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 4, 'TRT_ED': 4, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 2 } as Record<TraitId, number>,
      },
      {
        id: 'S06D',
        questionId: 'Q06',
        text: { en: `People tend to plan their work based on what their own team is doing, with limited visibility into what other teams are working on or when their outputs will be ready.`, fr: `People tend to plan their work based on what their own team is doing, with limited visibility into what other teams are working on or when their outputs will be ready.` },
        polarity: -1 as 1 | -1,
        tag: 'Adoption' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 2, 'TRT_CI': 4, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 4, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S06E',
        questionId: 'Q06',
        text: { en: `Collaboration works well between teams with a shared history, but breaks down when the strategy requires new partnerships between teams that have not collaborated before.`, fr: `Collaboration works well between teams with a shared history, but breaks down when the strategy requires new partnerships between teams that have not collaborated before.` },
        polarity: -1 as 1 | -1,
        tag: 'Adoption' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 4, 'TRT_ED': 0, 'TRT_AC': 2, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 4 } as Record<TraitId, number>,
      },
    ],
  },
  {
    id: 'Q07',
    dimensionId: 'D4' as DimensionId,
    text: { en: `How mature is the organisation's goal-setting capability — are goals outcome-oriented, measurable, and coherent across teams?`, fr: `How mature is the organisation's goal-setting capability — are goals outcome-oriented, measurable, and coherent across teams?` },
    contextPrompt: { en: `Pick a team-level OKR or goal from the current cycle. How clearly does it connect to a measurable strategic outcome? Would you know if it succeeded?`, fr: `Pick a team-level OKR or goal from the current cycle. How clearly does it connect to a measurable strategic outcome? Would you know if it succeeded?` },
    statements: [
      {
        id: 'S07A',
        questionId: 'Q07',
        text: { en: `Most goals are framed as activities or deliverables ('launch X', 'implement Y') rather than as outcomes that describe the change or impact the work should achieve.`, fr: `Most goals are framed as activities or deliverables ('launch X', 'implement Y') rather than as outcomes that describe the change or impact the work should achieve.` },
        polarity: -1 as 1 | -1,
        tag: 'Adoption' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 2, 'TRT_CI': 0, 'TRT_ED': 6, 'TRT_AC': 0, 'TRT_II': 2, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S07B',
        questionId: 'Q07',
        text: { en: `Goals are set ambitiously at the top level but become progressively vaguer as they cascade — by the time they reach delivery teams, the connection to a measurable outcome has been lost.`, fr: `Goals are set ambitiously at the top level but become progressively vaguer as they cascade — by the time they reach delivery teams, the connection to a measurable outcome has been lost.` },
        polarity: -1 as 1 | -1,
        tag: 'Adoption' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 3, 'TRT_CI': 0, 'TRT_ED': 4, 'TRT_AC': 0, 'TRT_II': 3, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S07C',
        questionId: 'Q07',
        text: { en: `Different managers frequently set goals that compete for the same resources without realising it — the conflict only surfaces when teams are pulled in opposing directions.`, fr: `Different managers frequently set goals that compete for the same resources without realising it — the conflict only surfaces when teams are pulled in opposing directions.` },
        polarity: -1 as 1 | -1,
        tag: 'Design' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 3, 'TRT_SA': 5, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 2, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S07D',
        questionId: 'Q07',
        text: { en: `Success metrics are defined, but many are not genuinely measurable — they use language like 'improve' or 'enhance' without specifying evidence of success.`, fr: `Success metrics are defined, but many are not genuinely measurable — they use language like 'improve' or 'enhance' without specifying evidence of success.` },
        polarity: -1 as 1 | -1,
        tag: 'Adoption' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 5, 'TRT_AC': 0, 'TRT_II': 3, 'TRT_DC': 2, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S07E',
        questionId: 'Q07',
        text: { en: `The organisation has invested in building goal-setting capability, and most teams can write outcome-oriented, measurable goals — though quality still varies across functions.`, fr: `The organisation has invested in building goal-setting capability, and most teams can write outcome-oriented, measurable goals — though quality still varies across functions.` },
        polarity: 1 as 1 | -1,
        tag: 'Both' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 3, 'TRT_CI': 0, 'TRT_ED': 4, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 3 } as Record<TraitId, number>,
      },
    ],
  },
  {
    id: 'Q08',
    dimensionId: 'D4' as DimensionId,
    text: { en: `Are goals translated into sequenced, cross-team delivery plans — or do they exist as ambitions without a roadmap?`, fr: `Are goals translated into sequenced, cross-team delivery plans — or do they exist as ambitions without a roadmap?` },
    contextPrompt: { en: `When two initiatives compete for the same engineering or specialist capacity, how is the conflict resolved? Is the trade-off visible and deliberate?`, fr: `When two initiatives compete for the same engineering or specialist capacity, how is the conflict resolved? Is the trade-off visible and deliberate?` },
    statements: [
      {
        id: 'S08A',
        questionId: 'Q08',
        text: { en: `Goals exist as ambitions, but there is no systematic process for translating them into sequenced work across teams.`, fr: `Goals exist as ambitions, but there is no systematic process for translating them into sequenced work across teams.` },
        polarity: -1 as 1 | -1,
        tag: 'Design' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 2, 'TRT_CI': 3, 'TRT_ED': 5, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S08B',
        questionId: 'Q08',
        text: { en: `Dependency mapping is rarely done upfront — teams frequently discover they are blocked because another team has not prioritised the same prerequisite.`, fr: `Dependency mapping is rarely done upfront — teams frequently discover they are blocked because another team has not prioritised the same prerequisite.` },
        polarity: -1 as 1 | -1,
        tag: 'Adoption' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 4, 'TRT_ED': 4, 'TRT_AC': 2, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S08C',
        questionId: 'Q08',
        text: { en: `Resource conflicts between strategic initiatives are resolved through escalation and politics rather than through upfront sequencing that makes trade-offs visible.`, fr: `Resource conflicts between strategic initiatives are resolved through escalation and politics rather than through upfront sequencing that makes trade-offs visible.` },
        polarity: -1 as 1 | -1,
        tag: 'Adoption' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 3, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 4, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 3, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S08D',
        questionId: 'Q08',
        text: { en: `The organisation has a process for translating goals into cross-team delivery plans, including upfront dependency mapping — though it is still being refined.`, fr: `The organisation has a process for translating goals into cross-team delivery plans, including upfront dependency mapping — though it is still being refined.` },
        polarity: 1 as 1 | -1,
        tag: 'Design' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 3, 'TRT_ED': 4, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 3 } as Record<TraitId, number>,
      },
      {
        id: 'S08E',
        questionId: 'Q08',
        text: { en: `Individual teams often have well-constructed execution plans, but these plans are not connected to each other — nobody has a view of how the pieces fit together.`, fr: `Individual teams often have well-constructed execution plans, but these plans are not connected to each other — nobody has a view of how the pieces fit together.` },
        polarity: -1 as 1 | -1,
        tag: 'Adoption' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 3, 'TRT_CI': 5, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 2, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
    ],
  },
  {
    id: 'Q09',
    dimensionId: 'D5' as DimensionId,
    text: { en: `Can leaders see an integrated view of progress toward strategic ambitions — or is reporting siloed and disconnected?`, fr: `Can leaders see an integrated view of progress toward strategic ambitions — or is reporting siloed and disconnected?` },
    contextPrompt: { en: `If you needed to know right now whether a cross-functional strategic initiative was on track, how would you find out? How long would it take?`, fr: `If you needed to know right now whether a cross-functional strategic initiative was on track, how would you find out? How long would it take?` },
    statements: [
      {
        id: 'S09A',
        questionId: 'Q09',
        text: { en: `Teams report progress in their own formats — there is no standardised way to see how team-level work connects to strategic ambitions.`, fr: `Teams report progress in their own formats — there is no standardised way to see how team-level work connects to strategic ambitions.` },
        polarity: -1 as 1 | -1,
        tag: 'Design' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 3, 'TRT_CI': 0, 'TRT_ED': 2, 'TRT_AC': 0, 'TRT_II': 5, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S09B',
        questionId: 'Q09',
        text: { en: `When a strategic objective requires contributions from multiple functions, there is no single place where leaders can see integrated progress.`, fr: `When a strategic objective requires contributions from multiple functions, there is no single place where leaders can see integrated progress.` },
        polarity: -1 as 1 | -1,
        tag: 'Design' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 4, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 4, 'TRT_DC': 2, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S09C',
        questionId: 'Q09',
        text: { en: `Reporting is frequent and data-rich, but it focuses on operational activity rather than progress toward strategic outcomes.`, fr: `Reporting is frequent and data-rich, but it focuses on operational activity rather than progress toward strategic outcomes.` },
        polarity: -1 as 1 | -1,
        tag: 'Adoption' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 3, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 4, 'TRT_DC': 3, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S09D',
        questionId: 'Q09',
        text: { en: `There is a clear reporting structure that connects team-level progress to strategic ambitions, and leaders can see integrated cross-functional progress.`, fr: `There is a clear reporting structure that connects team-level progress to strategic ambitions, and leaders can see integrated cross-functional progress.` },
        polarity: 1 as 1 | -1,
        tag: 'Both' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 3, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 4, 'TRT_DC': 3, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S09E',
        questionId: 'Q09',
        text: { en: `Leaders rely heavily on informal channels to understand what is really happening, because formal reporting does not give them a reliable picture.`, fr: `Leaders rely heavily on informal channels to understand what is really happening, because formal reporting does not give them a reliable picture.` },
        polarity: -1 as 1 | -1,
        tag: 'Adoption' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 2, 'TRT_AC': 0, 'TRT_II': 5, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 3 } as Record<TraitId, number>,
      },
    ],
  },
  {
    id: 'Q10',
    dimensionId: 'D5' as DimensionId,
    text: { en: `How quickly does the organisation detect problems and course-correct — or does it persist with failing approaches until the damage is undeniable?`, fr: `How quickly does the organisation detect problems and course-correct — or does it persist with failing approaches until the damage is undeniable?` },
    contextPrompt: { en: `Think of an execution problem that was known at the working level before leaders became aware. How long was the delay? What caused it?`, fr: `Think of an execution problem that was known at the working level before leaders became aware. How long was the delay? What caused it?` },
    statements: [
      {
        id: 'S10A',
        questionId: 'Q10',
        text: { en: `Once plans are set, the organisation treats them as commitments that cannot be changed — revising goals or reallocating resources is seen as failure.`, fr: `Once plans are set, the organisation treats them as commitments that cannot be changed — revising goals or reallocating resources is seen as failure.` },
        polarity: -1 as 1 | -1,
        tag: 'Adoption' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 6, 'TRT_II': 0, 'TRT_DC': 2, 'TRT_LI': 0, 'TRT_CO': 2, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S10B',
        questionId: 'Q10',
        text: { en: `Problems are often visible at the working level long before they surface in formal reviews — by the time senior leaders learn about them, the window for early intervention has passed.`, fr: `Problems are often visible at the working level long before they surface in formal reviews — by the time senior leaders learn about them, the window for early intervention has passed.` },
        polarity: -1 as 1 | -1,
        tag: 'Adoption' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 3, 'TRT_II': 5, 'TRT_DC': 2, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S10C',
        questionId: 'Q10',
        text: { en: `The organisation responds quickly to high-visibility crises, but slower-burning issues tend to go unaddressed until they become urgent.`, fr: `The organisation responds quickly to high-visibility crises, but slower-burning issues tend to go unaddressed until they become urgent.` },
        polarity: -1 as 1 | -1,
        tag: 'Adoption' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 4, 'TRT_II': 2, 'TRT_DC': 4, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S10D',
        questionId: 'Q10',
        text: { en: `There is a regular cadence of review meetings where execution progress is assessed honestly, and leaders are willing to adjust based on what they learn.`, fr: `There is a regular cadence of review meetings where execution progress is assessed honestly, and leaders are willing to adjust based on what they learn.` },
        polarity: 1 as 1 | -1,
        tag: 'Both' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 4, 'TRT_II': 3, 'TRT_DC': 3, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S10E',
        questionId: 'Q10',
        text: { en: `When something goes wrong, the default response is to look for who is at fault rather than to understand what in the system allowed the problem to emerge.`, fr: `When something goes wrong, the default response is to look for who is at fault rather than to understand what in the system allowed the problem to emerge.` },
        polarity: -1 as 1 | -1,
        tag: 'Adoption' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 3, 'TRT_II': 0, 'TRT_DC': 3, 'TRT_LI': 0, 'TRT_CO': 4, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
    ],
  },
  {
    id: 'Q11a',
    dimensionId: 'D6' as DimensionId,
    text: { en: `Thinking specifically about your SENIOR leadership team (Board, ExCo, or equivalent) — how genuinely aligned are they on strategic priorities?`, fr: `Thinking specifically about your SENIOR leadership team (Board, ExCo, or equivalent) — how genuinely aligned are they on strategic priorities?` },
    contextPrompt: { en: `When the senior team disagrees, how is it resolved? Does the resolution hold — or does it get re-opened later?`, fr: `When the senior team disagrees, how is it resolved? Does the resolution hold — or does it get re-opened later?` },
    statements: [
      {
        id: 'S11aA',
        questionId: 'Q11a',
        text: { en: `Leaders publicly agree on the direction, but in private they express different priorities — the alignment is performative rather than genuine.`, fr: `Leaders publicly agree on the direction, but in private they express different priorities — the alignment is performative rather than genuine.` },
        polarity: -1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 5, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 3, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 2, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S11aB',
        questionId: 'Q11a',
        text: { en: `The senior team has genuinely debated the difficult trade-offs and members who initially disagreed have committed to supporting the collective decision.`, fr: `The senior team has genuinely debated the difficult trade-offs and members who initially disagreed have committed to supporting the collective decision.` },
        polarity: 1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 4, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 3, 'TRT_CO': 3, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S11aC',
        questionId: 'Q11a',
        text: { en: `Different members signal different priorities to their respective organisations — creating confusion when priorities compete.`, fr: `Different members signal different priorities to their respective organisations — creating confusion when priorities compete.` },
        polarity: -1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 5, 'TRT_CI': 2, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 3, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S11aD',
        questionId: 'Q11a',
        text: { en: `The senior team functions more as a collection of functional heads advocating for their own areas than as an integrated team making collective decisions.`, fr: `The senior team functions more as a collection of functional heads advocating for their own areas than as an integrated team making collective decisions.` },
        polarity: -1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 4, 'TRT_CI': 4, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 2, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S11aE',
        questionId: 'Q11a',
        text: { en: `The senior team has a shared language and frameworks for discussing strategy — they can debate constructively without it becoming positional.`, fr: `The senior team has a shared language and frameworks for discussing strategy — they can debate constructively without it becoming positional.` },
        polarity: 1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 3, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 4, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 3 } as Record<TraitId, number>,
      },
    ],
  },
  {
    id: 'Q11b',
    dimensionId: 'D6' as DimensionId,
    text: { en: `Now thinking about the NEXT layer of leadership (directors, senior managers, department heads below the senior team) — how well does alignment cascade from the top?`, fr: `Now thinking about the NEXT layer of leadership (directors, senior managers, department heads below the senior team) — how well does alignment cascade from the top?` },
    contextPrompt: { en: `Think of a strategic commitment made by the senior team. Did it translate consistently into action at the next layer? If not, where did it break down?`, fr: `Think of a strategic commitment made by the senior team. Did it translate consistently into action at the next layer? If not, where did it break down?` },
    statements: [
      {
        id: 'S11bA',
        questionId: 'Q11b',
        text: { en: `The senior team is aligned, but this alignment does not reliably translate into consistent action at the next leadership layer — commitments soften as they cascade.`, fr: `The senior team is aligned, but this alignment does not reliably translate into consistent action at the next leadership layer — commitments soften as they cascade.` },
        polarity: -1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 4, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 3, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 3, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S11bB',
        questionId: 'Q11b',
        text: { en: `The next layer of leaders understands and actively supports the strategic direction — they translate it into their own context and drive it through their teams.`, fr: `The next layer of leaders understands and actively supports the strategic direction — they translate it into their own context and drive it through their teams.` },
        polarity: 1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 3, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 3, 'TRT_CO': 4, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S11bC',
        questionId: 'Q11b',
        text: { en: `Some leaders at the next layer are visibly resistant or sceptical — they comply with directives but do not actively drive the strategy.`, fr: `Some leaders at the next layer are visibly resistant or sceptical — they comply with directives but do not actively drive the strategy.` },
        polarity: -1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 3, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 2, 'TRT_CO': 5, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S11bD',
        questionId: 'Q11b',
        text: { en: `The next layer was not meaningfully involved in shaping the strategy — they received it rather than co-created it, and this shows in their commitment level.`, fr: `The next layer was not meaningfully involved in shaping the strategy — they received it rather than co-created it, and this shows in their commitment level.` },
        polarity: -1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 2, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 2, 'TRT_DC': 0, 'TRT_LI': 2, 'TRT_CO': 4, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S11bE',
        questionId: 'Q11b',
        text: { en: `Senior leaders have invested in helping the next layer understand the strategy's implications for their specific area — not just broadcasting the message.`, fr: `Senior leaders have invested in helping the next layer understand the strategy's implications for their specific area — not just broadcasting the message.` },
        polarity: 1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 3, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 4, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 3, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
    ],
  },
  {
    id: 'Q12',
    dimensionId: 'D6' as DimensionId,
    text: { en: `How strong is the leadership team's collective ability to read execution challenges accurately and choose the right interventions?`, fr: `How strong is the leadership team's collective ability to read execution challenges accurately and choose the right interventions?` },
    contextPrompt: { en: `Think of a recent execution problem. How was it diagnosed? Did the chosen intervention address the root cause, or did it treat a symptom?`, fr: `Think of a recent execution problem. How was it diagnosed? Did the chosen intervention address the root cause, or did it treat a symptom?` },
    statements: [
      {
        id: 'S12A',
        questionId: 'Q12',
        text: { en: `When execution runs into trouble, the default response tends to be 'communicate more' or 'try harder' — there is limited ability to distinguish whether the real issue is structural, capability-related, motivational, or something else.`, fr: `When execution runs into trouble, the default response tends to be 'communicate more' or 'try harder' — there is limited ability to distinguish whether the real issue is structural, capability-related, motivational, or something else.` },
        polarity: -1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 2, 'TRT_II': 0, 'TRT_DC': 6, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 2 } as Record<TraitId, number>,
      },
      {
        id: 'S12B',
        questionId: 'Q12',
        text: { en: `Leaders tend to apply the same management approach regardless of the situation — there is little adaptation of style or intervention type based on the specific nature of the problem.`, fr: `Leaders tend to apply the same management approach regardless of the situation — there is little adaptation of style or intervention type based on the specific nature of the problem.` },
        polarity: -1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 3, 'TRT_II': 0, 'TRT_DC': 5, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 2 } as Record<TraitId, number>,
      },
      {
        id: 'S12C',
        questionId: 'Q12',
        text: { en: `The leadership team has a track record of accurately diagnosing execution problems and matching the right intervention to the right root cause — including knowing when to leave things alone.`, fr: `The leadership team has a track record of accurately diagnosing execution problems and matching the right intervention to the right root cause — including knowing when to leave things alone.` },
        polarity: 1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 3, 'TRT_II': 0, 'TRT_DC': 5, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 2 } as Record<TraitId, number>,
      },
      {
        id: 'S12D',
        questionId: 'Q12',
        text: { en: `Leaders are strong at diagnosing issues within their own function but struggle to read cross-functional or systemic problems — they tend to see the piece of the elephant closest to them.`, fr: `Leaders are strong at diagnosing issues within their own function but struggle to read cross-functional or systemic problems — they tend to see the piece of the elephant closest to them.` },
        polarity: -1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 4, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 4, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 2 } as Record<TraitId, number>,
      },
      {
        id: 'S12E',
        questionId: 'Q12',
        text: { en: `When feedback surfaces about execution difficulties, leaders sometimes react defensively or dismiss the signal rather than treating it as diagnostic information.`, fr: `When feedback surfaces about execution difficulties, leaders sometimes react defensively or dismiss the signal rather than treating it as diagnostic information.` },
        polarity: -1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 3, 'TRT_DC': 4, 'TRT_LI': 0, 'TRT_CO': 3, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
    ],
  },
  {
    id: 'Q13',
    dimensionId: 'D6' as DimensionId,
    text: { en: `Do the leaders who will drive deployment have the credibility, relational trust, and influence needed to mobilise action across teams and stakeholders?`, fr: `Do the leaders who will drive deployment have the credibility, relational trust, and influence needed to mobilise action across teams and stakeholders?` },
    contextPrompt: { en: `Think of a leader in a critical deployment role. If they asked another team to reprioritise their work, would that team do it willingly — or would it require escalation?`, fr: `Think of a leader in a critical deployment role. If they asked another team to reprioritise their work, would that team do it willingly — or would it require escalation?` },
    statements: [
      {
        id: 'S13A',
        questionId: 'Q13',
        text: { en: `Some of the leaders who hold critical deployment roles have positional authority but lack the informal influence to get people to go beyond compliance.`, fr: `Some of the leaders who hold critical deployment roles have positional authority but lack the informal influence to get people to go beyond compliance.` },
        polarity: -1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 6, 'TRT_CO': 2, 'TRT_CF': 2 } as Record<TraitId, number>,
      },
      {
        id: 'S13B',
        questionId: 'Q13',
        text: { en: `The leaders driving deployment have strong, trust-based relationships across the organisation — people are willing to go the extra mile because they believe in and respect these leaders personally.`, fr: `The leaders driving deployment have strong, trust-based relationships across the organisation — people are willing to go the extra mile because they believe in and respect these leaders personally.` },
        polarity: 1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 2, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 5, 'TRT_CO': 3, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S13C',
        questionId: 'Q13',
        text: { en: `Leaders' credibility and influence is concentrated within their own function — when they need to mobilise action in other parts of the organisation, they struggle to gain traction without escalating.`, fr: `Leaders' credibility and influence is concentrated within their own function — when they need to mobilise action in other parts of the organisation, they struggle to gain traction without escalating.` },
        polarity: -1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 4, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 4, 'TRT_CO': 0, 'TRT_CF': 2 } as Record<TraitId, number>,
      },
      {
        id: 'S13D',
        questionId: 'Q13',
        text: { en: `There are specific leaders whose personal credibility is so strong that their involvement in an initiative significantly increases the likelihood of cross-functional cooperation.`, fr: `There are specific leaders whose personal credibility is so strong that their involvement in an initiative significantly increases the likelihood of cross-functional cooperation.` },
        polarity: 1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 3, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 5, 'TRT_CO': 2, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S13E',
        questionId: 'Q13',
        text: { en: `Some leaders have accumulated political capital but not trust-based capital — they can get compliance through transactional relationships, but cannot generate genuine commitment.`, fr: `Some leaders have accumulated political capital but not trust-based capital — they can get compliance through transactional relationships, but cannot generate genuine commitment.` },
        polarity: -1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 2, 'TRT_DC': 0, 'TRT_LI': 4, 'TRT_CO': 4, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
    ],
  },
  {
    id: 'Q14',
    dimensionId: 'D6' as DimensionId,
    text: { en: `Do the leaders responsible for executing the strategy have the specific experience, skills, and domain knowledge this particular strategy demands?`, fr: `Do the leaders responsible for executing the strategy have the specific experience, skills, and domain knowledge this particular strategy demands?` },
    contextPrompt: { en: `What is the single biggest execution challenge the new strategy presents? Which leader owns it, and have they done something like this before?`, fr: `What is the single biggest execution challenge the new strategy presents? Which leader owns it, and have they done something like this before?` },
    statements: [
      {
        id: 'S14A',
        questionId: 'Q14',
        text: { en: `The leadership team is strong in managing the current business, but the new strategy asks them to do things fundamentally different from their past experience — and these gaps have not been explicitly mapped.`, fr: `The leadership team is strong in managing the current business, but the new strategy asks them to do things fundamentally different from their past experience — and these gaps have not been explicitly mapped.` },
        polarity: -1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 2, 'TRT_II': 0, 'TRT_DC': 2, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 6 } as Record<TraitId, number>,
      },
      {
        id: 'S14B',
        questionId: 'Q14',
        text: { en: `Some leaders bring directly relevant experience from previous roles or organisations that will be valuable for the specific demands of the new strategy.`, fr: `Some leaders bring directly relevant experience from previous roles or organisations that will be valuable for the specific demands of the new strategy.` },
        polarity: 1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 2, 'TRT_LI': 2, 'TRT_CO': 0, 'TRT_CF': 6 } as Record<TraitId, number>,
      },
      {
        id: 'S14C',
        questionId: 'Q14',
        text: { en: `Where leadership skill gaps exist, the organisation has identified them and has plans in place — whether through targeted development, coaching, advisory support, or recruitment.`, fr: `Where leadership skill gaps exist, the organisation has identified them and has plans in place — whether through targeted development, coaching, advisory support, or recruitment.` },
        polarity: 1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 3, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 3, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 4 } as Record<TraitId, number>,
      },
      {
        id: 'S14D',
        questionId: 'Q14',
        text: { en: `The leadership team has been assembled primarily based on functional expertise and tenure rather than on fitness for the specific execution challenges the new strategy presents.`, fr: `The leadership team has been assembled primarily based on functional expertise and tenure rather than on fitness for the specific execution challenges the new strategy presents.` },
        polarity: -1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 3, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 2, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 5 } as Record<TraitId, number>,
      },
      {
        id: 'S14E',
        questionId: 'Q14',
        text: { en: `Leaders who have successfully led similar transformations or strategic shifts before are available to coach or support those facing this type of challenge for the first time.`, fr: `Leaders who have successfully led similar transformations or strategic shifts before are available to coach or support those facing this type of challenge for the first time.` },
        polarity: 1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 3, 'TRT_LI': 3, 'TRT_CO': 0, 'TRT_CF': 4 } as Record<TraitId, number>,
      },
    ],
  },
  {
    id: 'Q15',
    dimensionId: 'D7' as DimensionId,
    text: { en: `How well does the organisation translate strategic intent into language that enables people at every level to understand what it means for their own work?`, fr: `How well does the organisation translate strategic intent into language that enables people at every level to understand what it means for their own work?` },
    contextPrompt: { en: `Pick someone two levels below the senior team. If you asked them to explain what the strategy means for their daily work, how confident are you they could?`, fr: `Pick someone two levels below the senior team. If you asked them to explain what the strategy means for their daily work, how confident are you they could?` },
    statements: [
      {
        id: 'S15A',
        questionId: 'Q15',
        text: { en: `The strategy has been presented at town halls or in documents, but most people below the senior team would struggle to explain what specifically needs to change in their own work.`, fr: `The strategy has been presented at town halls or in documents, but most people below the senior team would struggle to explain what specifically needs to change in their own work.` },
        polarity: -1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 3, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 4, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 3, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S15B',
        questionId: 'Q15',
        text: { en: `Translation of the strategy into local context depends entirely on individual managers — some teams have a rich understanding while others have received only generic messaging.`, fr: `Translation of the strategy into local context depends entirely on individual managers — some teams have a rich understanding while others have received only generic messaging.` },
        polarity: -1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 4, 'TRT_DC': 0, 'TRT_LI': 3, 'TRT_CO': 3, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S15C',
        questionId: 'Q15',
        text: { en: `People understand the headline direction, but the practical implications — which projects to prioritise, which trade-offs to make, which legacy activities to stop — have not been made explicit.`, fr: `People understand the headline direction, but the practical implications — which projects to prioritise, which trade-offs to make, which legacy activities to stop — have not been made explicit.` },
        polarity: -1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 3, 'TRT_CI': 0, 'TRT_ED': 3, 'TRT_AC': 0, 'TRT_II': 4, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S15D',
        questionId: 'Q15',
        text: { en: `The organisation has invested in translating the strategy into function-specific and level-specific language, so that people can see what it means for their daily priorities and decisions.`, fr: `The organisation has invested in translating the strategy into function-specific and level-specific language, so that people can see what it means for their daily priorities and decisions.` },
        polarity: 1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 3, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 4, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 3, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S15E',
        questionId: 'Q15',
        text: { en: `There is a risk that the strategic narrative sounds inspiring at the top level but becomes disconnected from operational reality as it moves through the organisation.`, fr: `There is a risk that the strategic narrative sounds inspiring at the top level but becomes disconnected from operational reality as it moves through the organisation.` },
        polarity: -1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 3, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 4, 'TRT_DC': 3, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
    ],
  },
  {
    id: 'Q16',
    dimensionId: 'D7' as DimensionId,
    text: { en: `How freely and reliably does critical information flow upward to leaders and laterally across teams?`, fr: `How freely and reliably does critical information flow upward to leaders and laterally across teams?` },
    contextPrompt: { en: `When was the last time a leader learned about a problem significantly later than the working-level team knew about it? What caused the delay?`, fr: `When was the last time a leader learned about a problem significantly later than the working-level team knew about it? What caused the delay?` },
    statements: [
      {
        id: 'S16A',
        questionId: 'Q16',
        text: { en: `Leaders are often the last to know about execution risks or customer concerns — by the time information reaches them, it has been filtered, delayed, or reframed to sound less alarming.`, fr: `Leaders are often the last to know about execution risks or customer concerns — by the time information reaches them, it has been filtered, delayed, or reframed to sound less alarming.` },
        polarity: -1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 2, 'TRT_II': 6, 'TRT_DC': 2, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S16B',
        questionId: 'Q16',
        text: { en: `Information flows relatively well within functions (vertically), but poorly across functions (laterally) — teams working on related objectives often don't know what the other is doing.`, fr: `Information flows relatively well within functions (vertically), but poorly across functions (laterally) — teams working on related objectives often don't know what the other is doing.` },
        polarity: -1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 4, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 4, 'TRT_DC': 2, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S16C',
        questionId: 'Q16',
        text: { en: `There are formal channels for upward communication, but people do not trust them to carry uncomfortable truths — the real conversations happen informally or not at all.`, fr: `There are formal channels for upward communication, but people do not trust them to carry uncomfortable truths — the real conversations happen informally or not at all.` },
        polarity: -1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 4, 'TRT_DC': 0, 'TRT_LI': 3, 'TRT_CO': 3, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S16D',
        questionId: 'Q16',
        text: { en: `Leaders actively seek out unfiltered information — they go to where the work happens, ask direct questions, and have created an environment where people can share the unvarnished reality.`, fr: `Leaders actively seek out unfiltered information — they go to where the work happens, ask direct questions, and have created an environment where people can share the unvarnished reality.` },
        polarity: 1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 4, 'TRT_DC': 3, 'TRT_LI': 0, 'TRT_CO': 3, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S16E',
        questionId: 'Q16',
        text: { en: `The organisation generates a lot of data and reporting, but it does not translate into genuine insight for decision-makers — there is information overload without information quality.`, fr: `The organisation generates a lot of data and reporting, but it does not translate into genuine insight for decision-makers — there is information overload without information quality.` },
        polarity: -1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 2, 'TRT_AC': 0, 'TRT_II': 5, 'TRT_DC': 3, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
    ],
  },
  {
    id: 'Q17',
    dimensionId: 'D8' as DimensionId,
    text: { en: `To what extent have the people who will carry the weight of deployment been meaningfully involved in shaping the execution approach?`, fr: `To what extent have the people who will carry the weight of deployment been meaningfully involved in shaping the execution approach?` },
    contextPrompt: { en: `How were middle managers involved in designing the execution approach? Were they consulted, co-creators, or recipients?`, fr: `How were middle managers involved in designing the execution approach? Were they consulted, co-creators, or recipients?` },
    statements: [
      {
        id: 'S17A',
        questionId: 'Q17',
        text: { en: `The deployment plan has been designed by a small group at the top — the people who will carry the weight of execution have received it rather than shaped it.`, fr: `The deployment plan has been designed by a small group at the top — the people who will carry the weight of execution have received it rather than shaped it.` },
        polarity: -1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 2, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 2, 'TRT_CO': 6, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S17B',
        questionId: 'Q17',
        text: { en: `Middle managers were consulted during the planning phase, and some of their input was incorporated — but many feel their involvement was more about being informed than being genuinely listened to.`, fr: `Middle managers were consulted during the planning phase, and some of their input was incorporated — but many feel their involvement was more about being informed than being genuinely listened to.` },
        polarity: -1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 3, 'TRT_DC': 0, 'TRT_LI': 2, 'TRT_CO': 5, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S17C',
        questionId: 'Q17',
        text: { en: `Key delivery leads and middle managers have been actively involved in designing how the strategy will be executed — they see their fingerprints on the plan and feel personal accountability for its success.`, fr: `Key delivery leads and middle managers have been actively involved in designing how the strategy will be executed — they see their fingerprints on the plan and feel personal accountability for its success.` },
        polarity: 1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 2, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 3, 'TRT_CO': 5, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S17D',
        questionId: 'Q17',
        text: { en: `There is visible energy and initiative-taking among the people who will lead deployment — they are volunteering for roles, proposing ideas, and pulling the work forward rather than waiting to be directed.`, fr: `There is visible energy and initiative-taking among the people who will lead deployment — they are volunteering for roles, proposing ideas, and pulling the work forward rather than waiting to be directed.` },
        polarity: 1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 2, 'TRT_CO': 5, 'TRT_CF': 3 } as Record<TraitId, number>,
      },
      {
        id: 'S17E',
        questionId: 'Q17',
        text: { en: `Some of the most capable middle managers are sceptical about the execution approach — not because they disagree with the strategy, but because they have seen previous deployment efforts fail.`, fr: `Some of the most capable middle managers are sceptical about the execution approach — not because they disagree with the strategy, but because they have seen previous deployment efforts fail.` },
        polarity: -1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 3, 'TRT_II': 3, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 4, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
    ],
  },
  {
    id: 'Q18',
    dimensionId: 'D8' as DimensionId,
    text: { en: `How well do current incentive structures actually reinforce the behaviours and outcomes the new strategy requires?`, fr: `How well do current incentive structures actually reinforce the behaviours and outcomes the new strategy requires?` },
    contextPrompt: { en: `What gets rewarded in practice — individual functional performance, or cross-functional contribution to strategic outcomes? Give an example of a recent promotion or recognition decision.`, fr: `What gets rewarded in practice — individual functional performance, or cross-functional contribution to strategic outcomes? Give an example of a recent promotion or recognition decision.` },
    statements: [
      {
        id: 'S18A',
        questionId: 'Q18',
        text: { en: `People are still evaluated and rewarded based on criteria that reflect the previous strategy — there has been no visible change to performance metrics, bonus structures, or promotion criteria.`, fr: `People are still evaluated and rewarded based on criteria that reflect the previous strategy — there has been no visible change to performance metrics, bonus structures, or promotion criteria.` },
        polarity: -1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 5, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 3, 'TRT_CF': 2 } as Record<TraitId, number>,
      },
      {
        id: 'S18B',
        questionId: 'Q18',
        text: { en: `The incentive system rewards individual functional performance, which will make it difficult to motivate the cross-functional collaboration and shared outcomes the strategy demands.`, fr: `The incentive system rewards individual functional performance, which will make it difficult to motivate the cross-functional collaboration and shared outcomes the strategy demands.` },
        polarity: -1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 4, 'TRT_CI': 4, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 2, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
      {
        id: 'S18C',
        questionId: 'Q18',
        text: { en: `Recognition and rewards are informal and manager-dependent — whether someone is recognised for strategic contribution depends on who their manager is rather than on a consistent practice.`, fr: `Recognition and rewards are informal and manager-dependent — whether someone is recognised for strategic contribution depends on who their manager is rather than on a consistent practice.` },
        polarity: -1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 3, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 4, 'TRT_CF': 3 } as Record<TraitId, number>,
      },
      {
        id: 'S18D',
        questionId: 'Q18',
        text: { en: `The organisation has reviewed its incentive structures in light of the new strategy and has made deliberate changes to ensure people are rewarded for the behaviours and outcomes that matter most.`, fr: `The organisation has reviewed its incentive structures in light of the new strategy and has made deliberate changes to ensure people are rewarded for the behaviours and outcomes that matter most.` },
        polarity: 1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 4, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 3, 'TRT_CF': 3 } as Record<TraitId, number>,
      },
      {
        id: 'S18E',
        questionId: 'Q18',
        text: { en: `There is a disconnect between what leaders say matters and what actually gets rewarded — the strategy talks about collaboration, speed, and customer focus, but promotions still go to people who protect their turf.`, fr: `There is a disconnect between what leaders say matters and what actually gets rewarded — the strategy talks about collaboration, speed, and customer focus, but promotions still go to people who protect their turf.` },
        polarity: -1 as 1 | -1,
        tag: '—' as DesignAdoptionTag,
        traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 4, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 3, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 3, 'TRT_CF': 0 } as Record<TraitId, number>,
      },
    ],
  },
]
