// ═══════════════════════════════════════
// ESD v2 — Content Data (Auto-generated)
// ═══════════════════════════════════════
// FR translations: placeholders use EN text. Replace with FR before launch.

import type { Dimension, Question, Statement, Trait, TraitId, DimensionId, Band, DesignAdoptionTag } from './types'

// ── Dimensions ──
export const DIMENSIONS: Dimension[] = [
 {
  id: 'D1' as DimensionId,
  name: { en: `Decision Rights & Governance`, fr: `Droits de Décision & Gouvernance` },
  system: 'Structural',
  weight: 0.15,
  hasDesignAdoption: true,
  description: { en: `Clarity of decision ownership, consultation, escalation, and governance speed.`, fr: `Clarté de la propriété des décisions, consultation, escalade et rapidité de gouvernance.` },
 },
 {
  id: 'D2' as DimensionId,
  name: { en: `Organisational Design & Role Clarity`, fr: `Design Organisationnel & Clarté des Rôles` },
  system: 'Structural',
  weight: 0.1,
  hasDesignAdoption: true,
  description: { en: `Fit between structure and strategy. Whether interfaces exist AND function.`, fr: `Adéquation entre structure et stratégie. Si les interfaces existent ET fonctionnent.` },
 },
 {
  id: 'D3' as DimensionId,
  name: { en: `Coordination & Synchronisation`, fr: `Coordination & Synchronisation` },
  system: 'Structural',
  weight: 0.15,
  hasDesignAdoption: true,
  description: { en: `Accountability for coordination, predictability of cross-team working.`, fr: `Responsabilité de la coordination, prévisibilité du travail inter-équipes.` },
 },
 {
  id: 'D4' as DimensionId,
  name: { en: `Goal Architecture & OKR Maturity`, fr: `Architecture des Objectifs & Maturité OKR` },
  system: 'Structural',
  weight: 0.12,
  hasDesignAdoption: true,
  description: { en: `Goal quality, dependency management, roadmap sequencing.`, fr: `Qualité des objectifs, gestion des dépendances, séquencement de la feuille de route.` },
 },
 {
  id: 'D5' as DimensionId,
  name: { en: `Performance Tracking & Adaptation`, fr: `Suivi de la Performance & Adaptation` },
  system: 'Structural',
  weight: 0.1,
  hasDesignAdoption: true,
  description: { en: `Line of sight, reporting coherence, signal detection, adaptive capacity.`, fr: `Visibilité claire, cohérence du reporting, détection des signaux, capacité d'adaptation.` },
 },
 {
  id: 'D6' as DimensionId,
  name: { en: `Leadership Alignment & Capability`, fr: `Alignement & Capacité du Leadership` },
  system: 'Social',
  weight: 0.18,
  hasDesignAdoption: false,
  description: { en: `Senior team cohesion, cascade, diagnostic capability, social capital, capability-strategy fit.`, fr: `Cohésion de l'équipe dirigeante, cascade, capacité diagnostique, capital social, adéquation capacités-stratégie.` },
 },
 {
  id: 'D7' as DimensionId,
  name: { en: `Communication & Sensemaking`, fr: `Communication & Mise en Cohérence` },
  system: 'Social',
  weight: 0.1,
  hasDesignAdoption: false,
  description: { en: `Strategy translation, information flow upward and lateral.`, fr: `Traduction de la stratégie, flux d'information ascendant et latéral.` },
 },
 {
  id: 'D8' as DimensionId,
  name: { en: `Commitment, Ownership & Incentives`, fr: `Engagement, Appropriation & Incitations` },
  system: 'Social',
  weight: 0.1,
  hasDesignAdoption: false,
  description: { en: `Ownership depth, involvement quality, incentive alignment.`, fr: `Profondeur de l'appropriation, qualité de l'implication, alignement des incitations.` },
 },
]

// ── Traits ──
export const TRAITS: Trait[] = [
 {
  id: 'TRT_CA' as TraitId,
  name: { en: `Clarity of Authority`, fr: `Clarté de l'Autorité` },
  description: { en: `How clearly ownership, accountability, and decision-making power are defined.`, fr: `À quel point la propriété, la responsabilité et le pouvoir de décision sont clairement définis.` },
  interventionCriticalRed: { en: `Build a Decisions RACI for the top 15–20 contested decisions. Name singular accountable owners.`, fr: `Construire un RACI Décisions pour les 15-20 décisions les plus contestées. Nommer un responsable unique pour chacune.` },
  interventionAmber: { en: `Clarify authority at the specific cross-functional interfaces most critical to the strategy.`, fr: `Clarifier l'autorité aux interfaces transversales les plus critiques pour la stratégie.` },
 },
 {
  id: 'TRT_SA' as TraitId,
  name: { en: `Strategic Alignment`, fr: `Alignement Stratégique` },
  description: { en: `How consistently all elements point in the same strategic direction.`, fr: `À quel point tous les éléments convergent vers la même ambition stratégique.` },
  interventionCriticalRed: { en: `Conduct a strategic alignment audit: do structure, goals, incentives, and leadership signals all point the same way? Fix contradictions.`, fr: `Réaliser un audit d'alignement stratégique : structure, objectifs, incitations et signaux du leadership convergent-ils ? Corriger les contradictions.` },
  interventionAmber: { en: `Identify and resolve the 2–3 most visible contradictions between strategy messaging and system signals.`, fr: `Identifier et résoudre les 2-3 contradictions les plus visibles entre le message stratégique et les signaux du système.` },
 },
 {
  id: 'TRT_CI' as TraitId,
  name: { en: `Cross-boundary Integration`, fr: `Intégration Transversale` },
  description: { en: `Ability to work effectively across functions, teams, and business units.`, fr: `Capacité à travailler efficacement entre fonctions, équipes et unités d'affaires.` },
  interventionCriticalRed: { en: `Assign coordination owners for every critical cross-functional workstream. Design handover protocols. Create shared working rhythms.`, fr: `Désigner des responsables de coordination pour chaque chantier transversal critique. Concevoir des protocoles de transfert. Créer des rythmes de travail partagés.` },
  interventionAmber: { en: `Strengthen coordination mechanisms for the highest-priority cross-functional workstreams. Address structural barriers to collaboration.`, fr: `Renforcer les mécanismes de coordination pour les chantiers transversaux prioritaires. Lever les freins structurels à la collaboration.` },
 },
 {
  id: 'TRT_ED' as TraitId,
  name: { en: `Execution Discipline`, fr: `Discipline d'Exécution` },
  description: { en: `Rigour of goal-setting, dependency management, and roadmap sequencing.`, fr: `Rigueur dans la définition des objectifs, la gestion des dépendances et le séquencement.` },
  interventionCriticalRed: { en: `Implement OKR quality gates, dependency mapping, and cross-team delivery planning before scaling.`, fr: `Mettre en place des contrôles qualité OKR, une cartographie des dépendances et une planification inter-équipes avant de monter en puissance.` },
  interventionAmber: { en: `Improve goal quality through coaching and review. Extend dependency mapping to all deployment-critical workstreams.`, fr: `Améliorer la qualité des objectifs par le coaching et la revue. Étendre la cartographie des dépendances à tous les chantiers critiques.` },
 },
 {
  id: 'TRT_AC' as TraitId,
  name: { en: `Adaptive Capacity`, fr: `Capacité d'Adaptation` },
  description: { en: `Speed and effectiveness of detecting problems, learning, and adjusting course.`, fr: `Rapidité et efficacité de la détection des problèmes, de l'apprentissage et de l'ajustement.` },
  interventionCriticalRed: { en: `Establish shorter feedback loops. Deploy leading indicators. Create safe mechanisms for surfacing problems early.`, fr: `Établir des boucles de retour plus courtes. Mettre en place des indicateurs avancés. Créer des mécanismes sûrs pour faire remonter les problèmes tôt.` },
  interventionAmber: { en: `Reduce the time between problem emergence and leadership awareness. Build learning-from-failure protocols.`, fr: `Réduire le délai entre l'émergence d'un problème et sa prise de conscience par les dirigeants. Construire des protocoles d'apprentissage par l'échec.` },
 },
 {
  id: 'TRT_II' as TraitId,
  name: { en: `Information Integrity`, fr: `Intégrité de l'Information` },
  description: { en: `How freely, quickly, and honestly critical information moves.`, fr: `À quel point l'information critique circule librement, rapidement et honnêtement.` },
  interventionCriticalRed: { en: `Create unfiltered upward communication channels. Shift from blame-oriented to system-oriented responses. Leaders must actively seek bad news.`, fr: `Créer des canaux de communication ascendante non filtrés. Passer d'une culture du blâme à une approche systémique. Les dirigeants doivent rechercher les mauvaises nouvelles.` },
  interventionAmber: { en: `Identify and address the specific barriers to honest upward communication. Improve lateral information sharing across functions.`, fr: `Identifier et lever les obstacles à la communication ascendante honnête. Améliorer le partage d'information latéral entre fonctions.` },
 },
 {
  id: 'TRT_DC' as TraitId,
  name: { en: `Diagnostic Capability`, fr: `Capacité Diagnostique` },
  description: { en: `Leaders' ability to read execution challenges and match the right intervention.`, fr: `Capacité des dirigeants à lire les défis d'exécution et à choisir la bonne intervention.` },
  interventionCriticalRed: { en: `Invest in diagnostic frameworks: is this a structural, capability, motivational, or coordination problem? External facilitation for the first major challenge.`, fr: `Investir dans des cadres diagnostiques : est-ce un problème structurel, de capacité, de motivation ou de coordination ? Facilitation externe pour le premier défi majeur.` },
  interventionAmber: { en: `Build shared language for distinguishing problem types. Create a habit of root-cause analysis before intervention selection.`, fr: `Construire un langage partagé pour distinguer les types de problèmes. Créer l'habitude de l'analyse des causes racines avant le choix d'intervention.` },
 },
 {
  id: 'TRT_LI' as TraitId,
  name: { en: `Leadership Influence`, fr: `Influence du Leadership` },
  description: { en: `Credibility, trust, and relational capital to mobilise action beyond compliance.`, fr: `Crédibilité, confiance et capital relationnel pour mobiliser au-delà de la simple conformité.` },
  interventionCriticalRed: { en: `Invest in trust-based leadership development. Deploy high-credibility leaders to critical workstreams. Address credibility gaps honestly.`, fr: `Investir dans le développement du leadership fondé sur la confiance. Déployer des leaders à forte crédibilité sur les chantiers critiques. Traiter les déficits de crédibilité.` },
  interventionAmber: { en: `Identify leaders with strongest cross-functional influence and deploy them strategically. Provide support for leaders with credibility gaps.`, fr: `Identifier les leaders ayant la plus forte influence transversale et les déployer stratégiquement. Soutenir les leaders en déficit de crédibilité.` },
 },
 {
  id: 'TRT_CO' as TraitId,
  name: { en: `Collective Ownership`, fr: `Appropriation Collective` },
  description: { en: `Depth of genuine commitment, engagement, and shared purpose.`, fr: `Profondeur de l'engagement authentique, de l'implication et du sens partagé.` },
  interventionCriticalRed: { en: `Move from informing to co-creating. Involve middle managers in shaping execution approach. Address scepticism from past failures directly.`, fr: `Passer d'une logique d'information descendante à une véritable coconstruction. Impliquer l'encadrement intermédiaire dans l'approche d'exécution. Traiter le scepticisme lié aux échecs passés.` },
  interventionAmber: { en: `Deepen involvement of the next tier of delivery leads. Complete incentive realignment across critical functions.`, fr: `Renforcer l'implication du niveau suivant de responsables de mise en œuvre. Compléter le réalignement des incitations sur les fonctions critiques.` },
 },
 {
  id: 'TRT_CF' as TraitId,
  name: { en: `Capability-Strategy Fit`, fr: `Adéquation Capacités-Stratégie` },
  description: { en: `Match between what people can do and what this specific strategy demands.`, fr: `Adéquation entre ce que les collaborateurs savent faire et ce que cette stratégie exige.` },
  interventionCriticalRed: { en: `Conduct an honest capability-strategy fit assessment. Invest in targeted development, coaching, or recruitment where gaps are critical.`, fr: `Réaliser une évaluation honnête de l'adéquation capacités-stratégie. Investir dans le développement ciblé, le coaching ou le recrutement là où les écarts sont critiques.` },
  interventionAmber: { en: `Address the most critical capability gaps through coaching or advisory support. Accelerate development for leaders facing unfamiliar challenges.`, fr: `Traiter les écarts de capacité les plus critiques par le coaching ou l'accompagnement. Accélérer le développement des leaders confrontés à des défis nouveaux.` },
 },
]

// ── Questions ──
export const QUESTIONS: Question[] = [
 {
  id: 'Q01',
  dimensionId: 'D1' as DimensionId,
  text: { en: `How clearly defined are decision rights across the organisation — do people know who owns which decisions, who needs to be consulted, and who has final authority?`, fr: `Les droits de décision sont-ils clairement définis dans l'organisation — les collaborateurs savent-ils qui détient quelles décisions, qui doit être consulté et qui a l'autorité finale ?` },
  contextPrompt: { en: `Describe a recent decision that was difficult to resolve. What made it difficult — who was involved, what was contested, and how long did it take?`, fr: `Décrivez une décision récente difficile à résoudre. Qu'est-ce qui l'a rendue difficile — qui était impliqué, qu'est-ce qui a été contesté, et combien de temps cela a-t-il pris ?` },
  statements: [
   {
    id: 'S01A',
    questionId: 'Q01',
    text: { en: `When urgent decisions arise, they often bounce between people until someone senior steps in — because it's unclear who has the authority to make the call.`, fr: `Lorsqu'une décision urgente se pose, elle rebondit souvent entre les personnes jusqu'à ce qu'un dirigeant intervienne — car personne ne sait clairement qui a l'autorité pour trancher.` },
    polarity: -1 as 1 | -1,
    tag: 'Adoption' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 6, 'TRT_SA': 0, 'TRT_CI': 2, 'TRT_ED': 0, 'TRT_AC': 2, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S01B',
    questionId: 'Q01',
    text: { en: `Decision authority is well understood within each function, but at the cross-functional boundaries where the strategy needs coordination, ownership over decisions is ambiguous.`, fr: `L'autorité décisionnelle est bien comprise au sein de chaque fonction, mais aux interfaces transversales où la stratégie nécessite de la coordination, la propriété des décisions est ambiguë.` },
    polarity: -1 as 1 | -1,
    tag: 'Adoption' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 3, 'TRT_SA': 2, 'TRT_CI': 5, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S01C',
    questionId: 'Q01',
    text: { en: `A small number of senior leaders are the de facto decision-makers for almost everything — things work when they're available, but stall when they're not.`, fr: `Un petit nombre de dirigeants sont les décideurs de facto pour presque tout — les choses avancent quand ils sont disponibles, mais s'arrêtent quand ils ne le sont pas.` },
    polarity: -1 as 1 | -1,
    tag: 'Adoption' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 4, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 3, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 3, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S01D',
    questionId: 'Q01',
    text: { en: `People at middle management level generally know what they can decide on their own and escalate only when genuinely needed.`, fr: `Les cadres intermédiaires savent généralement ce qu'ils peuvent décider seuls et n'escaladent que lorsque c'est véritablement nécessaire.` },
    polarity: 1 as 1 | -1,
    tag: 'Adoption' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 5, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 2, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 3, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S01E',
    questionId: 'Q01',
    text: { en: `There is a documented decision framework (e.g., RACI or decision matrix) that has been reviewed for the new strategy and reflects how decisions actually get made — not just how they should get made on paper.`, fr: `Il existe un cadre décisionnel documenté (ex. RACI) revu pour la nouvelle stratégie et reflétant comment les décisions sont réellement prises — pas seulement comment elles devraient l'être sur le papier.` },
    polarity: 1 as 1 | -1,
    tag: 'Design' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 4, 'TRT_SA': 3, 'TRT_CI': 0, 'TRT_ED': 3, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
  ],
 },
 {
  id: 'Q02',
  dimensionId: 'D1' as DimensionId,
  text: { en: `How well does the current governance system support the speed and quality of decision-making the strategy demands?`, fr: `Dans quelle mesure le système de gouvernance actuel soutient-il la rapidité et la qualité de prise de décision que la stratégie exige ?` },
  contextPrompt: { en: `Think of a decision that should have been straightforward but wasn't. What slowed it down or caused it to be revisited?`, fr: `Dans quelle mesure le système de gouvernance actuel soutient-il la rapidité et la qualité de prise de décision que la stratégie exige ?` },
  statements: [
   {
    id: 'S02A',
    questionId: 'Q02',
    text: { en: `Most decisions pass through multiple approval layers before anything moves — even relatively routine ones require sign-offs that slow the process significantly.`, fr: `La plupart des décisions passent par plusieurs niveaux d'approbation avant que quoi que ce soit ne bouge — même les décisions courantes nécessitent des validations qui ralentissent significativement.` },
    polarity: -1 as 1 | -1,
    tag: 'Adoption' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 4, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 2, 'TRT_AC': 4, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S02B',
    questionId: 'Q02',
    text: { en: `Decisions get made at a reasonable pace, but they are frequently revisited or overridden afterward, which creates uncertainty about whether a decision is truly final.`, fr: `Les décisions sont prises à un rythme raisonnable, mais elles sont fréquemment remises en question ensuite, ce qui crée de l'incertitude sur leur caractère définitif.` },
    polarity: -1 as 1 | -1,
    tag: 'Adoption' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 5, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 3, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 2, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S02C',
    questionId: 'Q02',
    text: { en: `The governance system has been designed for the new strategy, but it has not yet been tested under real operating conditions — we don't know if it will hold under pressure.`, fr: `Le système de gouvernance a été conçu pour la nouvelle stratégie, mais il n'a pas encore été testé en conditions réelles — on ne sait pas s'il tiendra sous pression.` },
    polarity: -1 as 1 | -1,
    tag: 'Design' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 2, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 4, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 4 } as Record<TraitId, number>,
   },
   {
    id: 'S02D',
    questionId: 'Q02',
    text: { en: `Leaders regularly delegate decision-making to the appropriate level, and people feel empowered to act within their mandates without seeking unnecessary permission.`, fr: `Les dirigeants délèguent régulièrement la prise de décision au niveau approprié, et les collaborateurs se sentent habilités à agir dans leur mandat sans chercher de permission inutile.` },
    polarity: 1 as 1 | -1,
    tag: 'Adoption' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 4, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 3, 'TRT_CO': 3, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S02E',
    questionId: 'Q02',
    text: { en: `Governance forums and approval processes have been explicitly reviewed and reconfigured for the new strategy's demands — legacy structures have been retired or adapted.`, fr: `Les instances de gouvernance et les processus d'approbation ont été explicitement revus et reconfigurés pour les besoins de la nouvelle stratégie — les structures héritées ont été supprimées ou adaptées.` },
    polarity: 1 as 1 | -1,
    tag: 'Design' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 5, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 3, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 2 } as Record<TraitId, number>,
   },
  ],
 },
 {
  id: 'Q03',
  dimensionId: 'D2' as DimensionId,
  text: { en: `Does the current organisational structure create the right interfaces for the teams that need to collaborate on shared outcomes?`, fr: `La structure organisationnelle actuelle crée-t-elle les bonnes interfaces pour les équipes qui doivent collaborer sur des résultats communs ?` },
  contextPrompt: { en: `Which two teams need to collaborate most closely under the current strategy? How well does the structure support that collaboration?`, fr: `Quelles deux équipes doivent collaborer le plus étroitement ? Dans quelle mesure la structure soutient-elle cette collaboration ?` },
  statements: [
   {
    id: 'S03A',
    questionId: 'Q03',
    text: { en: `The teams that need to collaborate most closely currently sit in entirely separate parts of the organisation with no shared reporting, meetings, or natural interaction points.`, fr: `Les équipes qui doivent collaborer le plus étroitement sont dans des parties entièrement séparées de l'organisation sans reporting partagé ni points d'interaction naturels.` },
    polarity: -1 as 1 | -1,
    tag: 'Design' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 2, 'TRT_CI': 6, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 2 } as Record<TraitId, number>,
   },
   {
    id: 'S03B',
    questionId: 'Q03',
    text: { en: `Cross-functional forums exist, but they were designed for previous priorities and may not bring the right people together for the current strategy.`, fr: `Des forums transversaux existent, mais ils ont été conçus pour des priorités antérieures et pourraient ne pas réunir les bonnes personnes pour la stratégie actuelle.` },
    polarity: -1 as 1 | -1,
    tag: 'Design' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 3, 'TRT_CI': 4, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 3 } as Record<TraitId, number>,
   },
   {
    id: 'S03C',
    questionId: 'Q03',
    text: { en: `The organisation has recently restructured to create the right interfaces, but the new interfaces have not yet developed effective working relationships — the structure is right but the collaboration muscle is untested.`, fr: `L'organisation s'est récemment restructurée pour créer les bonnes interfaces, mais celles-ci n'ont pas encore développé de relations de travail efficaces — la structure est bonne mais le muscle de la collaboration n'a pas été testé.` },
    polarity: -1 as 1 | -1,
    tag: 'Adoption' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 2, 'TRT_CI': 5, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 3 } as Record<TraitId, number>,
   },
   {
    id: 'S03D',
    questionId: 'Q03',
    text: { en: `The organisation has recently restructured or realigned teams in ways that create most of the interfaces the strategy needs, and these interfaces are starting to function.`, fr: `L'organisation a récemment restructuré ou réaligné les équipes pour créer la plupart des interfaces dont la stratégie a besoin, et ces interfaces commencent à fonctionner.` },
    polarity: 1 as 1 | -1,
    tag: 'Both' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 4, 'TRT_CI': 4, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 2 } as Record<TraitId, number>,
   },
   {
    id: 'S03E',
    questionId: 'Q03',
    text: { en: `People have developed informal workarounds — relationships, back-channels, ad hoc meetings — to compensate for structural gaps, but these depend on specific individuals and are fragile.`, fr: `Les collaborateurs ont développé des contournements informels — relations, canaux parallèles, réunions ad hoc — pour compenser les lacunes structurelles, mais ceux-ci dépendent d'individus spécifiques et sont fragiles.` },
    polarity: -1 as 1 | -1,
    tag: 'Adoption' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 4, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 3, 'TRT_CO': 0, 'TRT_CF': 3 } as Record<TraitId, number>,
   },
  ],
 },
 {
  id: 'Q04',
  dimensionId: 'D2' as DimensionId,
  text: { en: `How clearly defined are roles, responsibilities, and mandates — particularly at the boundaries where functions need to hand off work or make joint decisions?`, fr: `Les rôles, responsabilités et mandats sont-ils clairement définis — en particulier aux interfaces où les fonctions doivent se passer le relais ou prendre des décisions conjointes ?` },
  contextPrompt: { en: `Describe a recent hand-off between teams. Was it clean or messy? What caused the friction?`, fr: `Décrivez un récent passage de relais entre équipes. Était-ce fluide ou chaotique ? Qu'est-ce qui a causé la friction ?` },
  statements: [
   {
    id: 'S04A',
    questionId: 'Q04',
    text: { en: `Within functions, people generally know their role — but the moment work crosses a functional boundary, it becomes unclear who owns what, and things fall through the gaps.`, fr: `Au sein des fonctions, les collaborateurs connaissent généralement leur rôle — mais dès que le travail traverse une frontière fonctionnelle, il devient flou qui est responsable de quoi.` },
    polarity: -1 as 1 | -1,
    tag: 'Adoption' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 5, 'TRT_SA': 0, 'TRT_CI': 3, 'TRT_ED': 2, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S04B',
    questionId: 'Q04',
    text: { en: `Certain roles have been deliberately designed to sit at the intersection of functions, and these bridge roles genuinely help clarify who does what at the boundaries.`, fr: `Certains rôles ont été délibérément conçus à l'intersection des fonctions, et ces rôles de liaison aident véritablement à clarifier qui fait quoi aux interfaces.` },
    polarity: 1 as 1 | -1,
    tag: 'Design' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 3, 'TRT_SA': 0, 'TRT_CI': 4, 'TRT_ED': 3, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S04C',
    questionId: 'Q04',
    text: { en: `Role descriptions exist on paper, but people's actual scope has drifted from what is documented — stated responsibilities and real responsibilities don't match.`, fr: `Les descriptions de poste existent sur le papier, mais le périmètre réel des personnes a dérivé de ce qui est documenté — les responsabilités officielles et les responsabilités réelles ne correspondent plus.` },
    polarity: -1 as 1 | -1,
    tag: 'Adoption' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 4, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 3, 'TRT_AC': 0, 'TRT_II': 3, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S04D',
    questionId: 'Q04',
    text: { en: `When two teams need to hand off work, there is usually a period of confusion about who picks it up, who checks quality, and who is accountable if something goes wrong.`, fr: `Quand deux équipes doivent se passer le relais, il y a généralement une confusion sur qui prend la suite, qui vérifie la qualité et qui est responsable si quelque chose tourne mal.` },
    polarity: -1 as 1 | -1,
    tag: 'Adoption' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 4, 'TRT_SA': 0, 'TRT_CI': 4, 'TRT_ED': 2, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S04E',
    questionId: 'Q04',
    text: { en: `Leaders have recently or are currently clarifying roles and mandates in anticipation of the strategy's demands — this work is in progress but not yet complete.`, fr: `Les dirigeants ont récemment commencé ou sont en train de clarifier les rôles et mandats en prévision des exigences de la stratégie — ce travail est en cours mais pas encore finalisé.` },
    polarity: 1 as 1 | -1,
    tag: 'Design' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 3, 'TRT_SA': 4, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 3 } as Record<TraitId, number>,
   },
  ],
 },
 {
  id: 'Q05',
  dimensionId: 'D3' as DimensionId,
  text: { en: `Who explicitly owns cross-functional coordination — is there clear accountability for keeping shared work synchronised?`, fr: `Qui est explicitement responsable de la coordination transversale — y a-t-il une responsabilité explicite pour maintenir le travail partagé synchronisé ?` },
  contextPrompt: { en: `When two departments disagree about priorities or sequencing, how is it resolved? Who mediates?`, fr: `Quand deux départements sont en désaccord sur les priorités ou le séquencement, comment est-ce résolu ? Qui arbitre ?` },
  statements: [
   {
    id: 'S05A',
    questionId: 'Q05',
    text: { en: `When cross-functional work falls through the cracks, each function points to the other — nobody clearly owns the coordination space in between.`, fr: `Quand le travail transversal tombe entre les mailles, chaque fonction pointe vers l'autre — personne ne possède clairement l'espace de coordination intermédiaire.` },
    polarity: -1 as 1 | -1,
    tag: 'Adoption' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 5, 'TRT_SA': 0, 'TRT_CI': 3, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 2, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S05B',
    questionId: 'Q05',
    text: { en: `Coordination happens because specific individuals take it upon themselves — it is personality-driven rather than built into how the organisation operates.`, fr: `La coordination a lieu parce que des individus spécifiques prennent l'initiative — elle est portée par des personnalités plutôt qu'intégrée dans le fonctionnement de l'organisation.` },
    polarity: -1 as 1 | -1,
    tag: 'Adoption' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 4, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 3, 'TRT_CO': 0, 'TRT_CF': 3 } as Record<TraitId, number>,
   },
   {
    id: 'S05C',
    questionId: 'Q05',
    text: { en: `Certain major programmes have named coordinators, but the vast majority of cross-functional work has no explicit coordination owner.`, fr: `Certains programmes majeurs ont des coordinateurs nommés, mais la grande majorité du travail transversal n'a pas de responsable de coordination explicite.` },
    polarity: -1 as 1 | -1,
    tag: 'Design' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 4, 'TRT_SA': 0, 'TRT_CI': 4, 'TRT_ED': 2, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S05D',
    questionId: 'Q05',
    text: { en: `The organisation has established clear accountability for cross-functional coordination — named owners, established rhythms, and explicit mandates for keeping shared work synchronised.`, fr: `L'organisation a établi une responsabilité explicite pour la coordination transversale — des responsables désignés, des rythmes établis et des mandats explicites.` },
    polarity: 1 as 1 | -1,
    tag: 'Both' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 4, 'TRT_SA': 0, 'TRT_CI': 3, 'TRT_ED': 3, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S05E',
    questionId: 'Q05',
    text: { en: `Senior leaders assume coordination is happening because they have asked for it — but there is no mechanism to verify whether teams are actually synchronised.`, fr: `Les dirigeants seniors supposent que la coordination a lieu parce qu'ils l'ont demandée — mais il n'existe aucun mécanisme pour vérifier si les équipes sont réellement synchronisées.` },
    polarity: -1 as 1 | -1,
    tag: 'Adoption' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 2, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 4, 'TRT_DC': 4, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
  ],
 },
 {
  id: 'Q06',
  dimensionId: 'D3' as DimensionId,
  text: { en: `How predictable and reliable is cross-team working — can teams plan their own work with confidence about what other teams will deliver?`, fr: `Le travail inter-équipes est-il prévisible et fiable — les équipes peuvent-elles planifier leur travail en ayant confiance en ce que les autres livreront ?` },
  contextPrompt: { en: `Have you experienced a situation where a project was delayed because another team had different assumptions? What happened?`, fr: `Avez-vous vécu une situation où un projet a été retardé parce qu'une autre équipe avait des hypothèses différentes ? Que s'est-il passé ?` },
  statements: [
   {
    id: 'S06A',
    questionId: 'Q06',
    text: { en: `Teams regularly discover mid-project that another team has different assumptions about timelines, deliverables, or quality standards.`, fr: `Les équipes découvrent régulièrement en cours de projet qu'une autre équipe a des hypothèses différentes sur les délais, livrables ou standards de qualité.` },
    polarity: -1 as 1 | -1,
    tag: 'Adoption' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 4, 'TRT_ED': 3, 'TRT_AC': 0, 'TRT_II': 3, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S06B',
    questionId: 'Q06',
    text: { en: `Teams operate on incompatible planning rhythms, making it structurally difficult to synchronise work even when people want to.`, fr: `Les équipes opèrent sur des rythmes de planification incompatibles, rendant structurellement difficile la synchronisation même quand les collaborateurs le souhaitent.` },
    polarity: -1 as 1 | -1,
    tag: 'Design' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 2, 'TRT_CI': 4, 'TRT_ED': 4, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S06C',
    questionId: 'Q06',
    text: { en: `There are well-established shared processes for how teams work together — including common definitions of 'done', agreed handoff points, and compatible planning cycles.`, fr: `Il existe des processus partagés bien établis pour le travail inter-équipes — incluant des définitions communes du « terminé », des points de transfert convenus et des cycles de planification compatibles.` },
    polarity: 1 as 1 | -1,
    tag: 'Both' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 4, 'TRT_ED': 4, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 2 } as Record<TraitId, number>,
   },
   {
    id: 'S06D',
    questionId: 'Q06',
    text: { en: `People tend to plan their work based on what their own team is doing, with limited visibility into what other teams are working on or when their outputs will be ready.`, fr: `Les collaborateurs planifient leur travail en se basant sur ce que fait leur propre équipe, avec une visibilité limitée sur ce que font les autres équipes.` },
    polarity: -1 as 1 | -1,
    tag: 'Adoption' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 2, 'TRT_CI': 4, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 4, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S06E',
    questionId: 'Q06',
    text: { en: `Collaboration works well between teams with a shared history, but breaks down when the strategy requires new partnerships between teams that have not collaborated before.`, fr: `La collaboration fonctionne bien entre équipes ayant un historique commun, mais s'effondre quand la stratégie exige de nouveaux partenariats entre équipes qui n'ont jamais collaboré.` },
    polarity: -1 as 1 | -1,
    tag: 'Adoption' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 4, 'TRT_ED': 0, 'TRT_AC': 2, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 4 } as Record<TraitId, number>,
   },
  ],
 },
 {
  id: 'Q07',
  dimensionId: 'D4' as DimensionId,
  text: { en: `How mature is the organisation's goal-setting capability — are goals outcome-oriented, measurable, and coherent across teams?`, fr: `Quelle est la maturité de la capacité de fixation d'objectifs de l'organisation — les objectifs sont-ils orientés résultats, mesurables et cohérents entre les équipes ?` },
  contextPrompt: { en: `Pick a team-level OKR or goal from the current cycle. How clearly does it connect to a measurable strategic outcome? Would you know if it succeeded?`, fr: `Choisissez un OKR d'équipe du cycle en cours. À quel point se connecte-t-il à un résultat stratégique mesurable ? Sauriez-vous s'il a réussi ?` },
  statements: [
   {
    id: 'S07A',
    questionId: 'Q07',
    text: { en: `Most goals are framed as activities or deliverables ('launch X', 'implement Y') rather than as outcomes that describe the change or impact the work should achieve.`, fr: `La plupart des objectifs sont formulés comme des activités ou des livrables (« lancer X », « implémenter Y ») plutôt que comme des résultats décrivant le changement ou l'impact attendu.` },
    polarity: -1 as 1 | -1,
    tag: 'Adoption' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 2, 'TRT_CI': 0, 'TRT_ED': 6, 'TRT_AC': 0, 'TRT_II': 2, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S07B',
    questionId: 'Q07',
    text: { en: `Goals are set ambitiously at the top level but become progressively vaguer as they cascade — by the time they reach delivery teams, the connection to a measurable outcome has been lost.`, fr: `Les objectifs sont fixés ambitieusement au niveau supérieur mais deviennent progressivement plus vagues en cascadant — quand ils atteignent les équipes de livraison, le lien avec un résultat mesurable a été perdu.` },
    polarity: -1 as 1 | -1,
    tag: 'Adoption' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 3, 'TRT_CI': 0, 'TRT_ED': 4, 'TRT_AC': 0, 'TRT_II': 3, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S07C',
    questionId: 'Q07',
    text: { en: `Different managers frequently set goals that compete for the same resources without realising it — the conflict only surfaces when teams are pulled in opposing directions.`, fr: `Différents managers fixent fréquemment des objectifs qui se disputent les mêmes ressources sans s'en rendre compte — le conflit ne fait surface que lorsque les équipes sont tiraillées dans des directions opposées.` },
    polarity: -1 as 1 | -1,
    tag: 'Design' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 3, 'TRT_SA': 5, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 2, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S07D',
    questionId: 'Q07',
    text: { en: `Success metrics are defined, but many are not genuinely measurable — they use language like 'improve' or 'enhance' without specifying evidence of success.`, fr: `Des indicateurs de succès sont définis, mais beaucoup ne sont pas véritablement mesurables — ils utilisent un langage comme « améliorer » ou « renforcer » sans préciser les preuves de succès.` },
    polarity: -1 as 1 | -1,
    tag: 'Adoption' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 5, 'TRT_AC': 0, 'TRT_II': 3, 'TRT_DC': 2, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S07E',
    questionId: 'Q07',
    text: { en: `The organisation has invested in building goal-setting capability, and most teams can write outcome-oriented, measurable goals — though quality still varies across functions.`, fr: `L'organisation a investi dans le développement de la capacité de fixation d'objectifs, et la plupart des équipes savent rédiger des objectifs orientés résultats et mesurables — bien que la qualité varie encore selon les fonctions.` },
    polarity: 1 as 1 | -1,
    tag: 'Both' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 3, 'TRT_CI': 0, 'TRT_ED': 4, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 3 } as Record<TraitId, number>,
   },
  ],
 },
 {
  id: 'Q08',
  dimensionId: 'D4' as DimensionId,
  text: { en: `Are goals translated into sequenced, cross-team delivery plans — or do they exist as ambitions without a roadmap?`, fr: `Les objectifs sont-ils traduits en plans de livraison séquencés et inter-équipes — ou existent-ils comme des ambitions sans feuille de route ?` },
  contextPrompt: { en: `When two initiatives compete for the same engineering or specialist capacity, how is the conflict resolved? Is the trade-off visible and deliberate?`, fr: `Quand deux initiatives rivalisent pour la même capacité spécialisée, comment le conflit est-il résolu ? Le compromis est-il visible et délibéré ?` },
  statements: [
   {
    id: 'S08A',
    questionId: 'Q08',
    text: { en: `Goals exist as ambitions, but there is no systematic process for translating them into sequenced work across teams.`, fr: `Les objectifs existent en tant qu'ambitions, mais il n'y a pas de processus systématique pour les traduire en travail séquencé entre les équipes.` },
    polarity: -1 as 1 | -1,
    tag: 'Design' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 2, 'TRT_CI': 3, 'TRT_ED': 5, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S08B',
    questionId: 'Q08',
    text: { en: `Dependency mapping is rarely done upfront — teams frequently discover they are blocked because another team has not prioritised the same prerequisite.`, fr: `La cartographie des dépendances est rarement faite en amont — les équipes découvrent fréquemment qu'elles sont bloquées parce qu'une autre équipe n'a pas priorisé le même prérequis.` },
    polarity: -1 as 1 | -1,
    tag: 'Adoption' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 4, 'TRT_ED': 4, 'TRT_AC': 2, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S08C',
    questionId: 'Q08',
    text: { en: `Resource conflicts between strategic initiatives are resolved through escalation and politics rather than through upfront sequencing that makes trade-offs visible.`, fr: `Les conflits de ressources entre initiatives stratégiques sont résolus par l'escalade et la politique plutôt que par un séquencement préalable qui rend les arbitrages visibles.` },
    polarity: -1 as 1 | -1,
    tag: 'Adoption' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 3, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 4, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 3, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S08D',
    questionId: 'Q08',
    text: { en: `The organisation has a process for translating goals into cross-team delivery plans, including upfront dependency mapping — though it is still being refined.`, fr: `L'organisation dispose d'un processus pour traduire les objectifs en plans de livraison inter-équipes, incluant une cartographie préalable des dépendances — bien qu'il soit encore en cours d'amélioration.` },
    polarity: 1 as 1 | -1,
    tag: 'Design' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 3, 'TRT_ED': 4, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 3 } as Record<TraitId, number>,
   },
   {
    id: 'S08E',
    questionId: 'Q08',
    text: { en: `Individual teams often have well-constructed execution plans, but these plans are not connected to each other — nobody has a view of how the pieces fit together.`, fr: `Les équipes individuelles ont souvent des plans d'exécution bien construits, mais ces plans ne sont pas connectés les uns aux autres — personne n'a une vue d'ensemble de la façon dont les pièces s'assemblent.` },
    polarity: -1 as 1 | -1,
    tag: 'Adoption' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 3, 'TRT_CI': 5, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 2, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
  ],
 },
 {
  id: 'Q09',
  dimensionId: 'D5' as DimensionId,
  text: { en: `Can leaders see an integrated view of progress toward strategic ambitions — or is reporting siloed and disconnected?`, fr: `Les dirigeants peuvent-ils voir une vue intégrée de l'avancement vers les ambitions stratégiques — ou le reporting est-il cloisonné et déconnecté ?` },
  contextPrompt: { en: `If you needed to know right now whether a cross-functional strategic initiative was on track, how would you find out? How long would it take?`, fr: `Si vous deviez savoir maintenant si une initiative stratégique transversale était en bonne voie, comment le découvririez-vous ? Combien de temps faudrait-il ?` },
  statements: [
   {
    id: 'S09A',
    questionId: 'Q09',
    text: { en: `Teams report progress in their own formats — there is no standardised way to see how team-level work connects to strategic ambitions.`, fr: `Les équipes rendent compte de leurs progrès dans leurs propres formats — il n'y a pas de moyen standardisé de voir comment le travail d'équipe se rattache aux ambitions stratégiques.` },
    polarity: -1 as 1 | -1,
    tag: 'Design' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 3, 'TRT_CI': 0, 'TRT_ED': 2, 'TRT_AC': 0, 'TRT_II': 5, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S09B',
    questionId: 'Q09',
    text: { en: `When a strategic objective requires contributions from multiple functions, there is no single place where leaders can see integrated progress.`, fr: `Lorsqu'un objectif stratégique nécessite des contributions de plusieurs fonctions, il n'existe aucun endroit unique où les dirigeants peuvent voir les progrès intégrés.` },
    polarity: -1 as 1 | -1,
    tag: 'Design' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 4, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 4, 'TRT_DC': 2, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S09C',
    questionId: 'Q09',
    text: { en: `Reporting is frequent and data-rich, but it focuses on operational activity rather than progress toward strategic outcomes.`, fr: `Le reporting est fréquent et riche en données, mais il se concentre sur l'activité opérationnelle plutôt que sur les progrès vers les résultats stratégiques.` },
    polarity: -1 as 1 | -1,
    tag: 'Adoption' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 3, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 4, 'TRT_DC': 3, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S09D',
    questionId: 'Q09',
    text: { en: `There is a clear reporting structure that connects team-level progress to strategic ambitions, and leaders can see integrated cross-functional progress.`, fr: `Il existe une structure de reporting claire qui relie les progrès au niveau des équipes aux ambitions stratégiques, et les dirigeants peuvent voir les progrès transversaux intégrés.` },
    polarity: 1 as 1 | -1,
    tag: 'Both' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 3, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 4, 'TRT_DC': 3, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S09E',
    questionId: 'Q09',
    text: { en: `Leaders rely heavily on informal channels to understand what is really happening, because formal reporting does not give them a reliable picture.`, fr: `Les dirigeants s'appuient fortement sur des canaux informels pour comprendre ce qui se passe réellement, car le reporting formel ne leur donne pas une image fiable.` },
    polarity: -1 as 1 | -1,
    tag: 'Adoption' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 2, 'TRT_AC': 0, 'TRT_II': 5, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 3 } as Record<TraitId, number>,
   },
  ],
 },
 {
  id: 'Q10',
  dimensionId: 'D5' as DimensionId,
  text: { en: `How quickly does the organisation detect problems and course-correct — or does it persist with failing approaches until the damage is undeniable?`, fr: `À quelle vitesse l'organisation détecte-t-elle les problèmes et corrige-t-elle le tir — ou persiste-t-elle avec des approches défaillantes ?` },
  contextPrompt: { en: `Think of an execution problem that was known at the working level before leaders became aware. How long was the delay? What caused it?`, fr: `Pensez à un problème d'exécution connu au niveau opérationnel avant les dirigeants. Quel a été le délai ? Qu'est-ce qui l'a causé ?` },
  statements: [
   {
    id: 'S10A',
    questionId: 'Q10',
    text: { en: `Once plans are set, the organisation treats them as commitments that cannot be changed — revising goals or reallocating resources is seen as failure.`, fr: `Une fois les plans établis, l'organisation les traite comme des engagements inamovibles — réviser les objectifs ou réallouer les ressources est perçu comme un échec.` },
    polarity: -1 as 1 | -1,
    tag: 'Adoption' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 6, 'TRT_II': 0, 'TRT_DC': 2, 'TRT_LI': 0, 'TRT_CO': 2, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S10B',
    questionId: 'Q10',
    text: { en: `Problems are often visible at the working level long before they surface in formal reviews — by the time senior leaders learn about them, the window for early intervention has passed.`, fr: `Les problèmes sont souvent visibles au niveau opérationnel bien avant qu'ils ne remontent dans les revues formelles — quand les dirigeants en prennent connaissance, la fenêtre d'intervention précoce est passée.` },
    polarity: -1 as 1 | -1,
    tag: 'Adoption' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 3, 'TRT_II': 5, 'TRT_DC': 2, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S10C',
    questionId: 'Q10',
    text: { en: `The organisation responds quickly to high-visibility crises, but slower-burning issues tend to go unaddressed until they become urgent.`, fr: `L'organisation réagit rapidement aux crises visibles, mais les problèmes qui couvent lentement tendent à rester sans réponse jusqu'à ce qu'ils deviennent urgents.` },
    polarity: -1 as 1 | -1,
    tag: 'Adoption' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 4, 'TRT_II': 2, 'TRT_DC': 4, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S10D',
    questionId: 'Q10',
    text: { en: `There is a regular cadence of review meetings where execution progress is assessed honestly, and leaders are willing to adjust based on what they learn.`, fr: `Il existe une cadence régulière de réunions de revue où les progrès d'exécution sont évalués honnêtement, et les dirigeants sont prêts à s'ajuster en fonction de ce qu'ils apprennent.` },
    polarity: 1 as 1 | -1,
    tag: 'Both' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 4, 'TRT_II': 3, 'TRT_DC': 3, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S10E',
    questionId: 'Q10',
    text: { en: `When something goes wrong, the default response is to look for who is at fault rather than to understand what in the system allowed the problem to emerge.`, fr: `Quand quelque chose ne va pas, la réaction par défaut est de chercher un coupable plutôt que de comprendre ce qui, dans le système, a permis au problème d'émerger.` },
    polarity: -1 as 1 | -1,
    tag: 'Adoption' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 3, 'TRT_II': 0, 'TRT_DC': 3, 'TRT_LI': 0, 'TRT_CO': 4, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
  ],
 },
 {
  id: 'Q11a',
  dimensionId: 'D6' as DimensionId,
  text: { en: `Thinking specifically about your SENIOR leadership team (Board, ExCo, or equivalent) — how genuinely aligned are they on strategic priorities?`, fr: `En pensant spécifiquement à votre équipe de direction SENIOR (Conseil, ComEx ou équivalent) — à quel point sont-ils véritablement alignés sur les priorités stratégiques ?` },
  contextPrompt: { en: `When the senior team disagrees, how is it resolved? Does the resolution hold — or does it get re-opened later?`, fr: `Quand l'équipe dirigeante est en désaccord, comment est-ce résolu ? La résolution tient-elle — ou est-elle remise en question plus tard ?` },
  statements: [
   {
    id: 'S11aA',
    questionId: 'Q11a',
    text: { en: `Leaders publicly agree on the direction, but in private they express different priorities — the alignment is performative rather than genuine.`, fr: `Les dirigeants sont publiquement d'accord sur la direction, mais en privé ils expriment des priorités différentes — l'alignement est de façade plutôt que réel.` },
    polarity: -1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 5, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 3, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 2, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S11aB',
    questionId: 'Q11a',
    text: { en: `The senior team has genuinely debated the difficult trade-offs and members who initially disagreed have committed to supporting the collective decision.`, fr: `L'équipe dirigeante a véritablement débattu des arbitrages difficiles et les membres qui étaient initialement en désaccord se sont engagés à soutenir la décision collective.` },
    polarity: 1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 4, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 3, 'TRT_CO': 3, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S11aC',
    questionId: 'Q11a',
    text: { en: `Different members signal different priorities to their respective organisations — creating confusion when priorities compete.`, fr: `Différents membres signalent des priorités différentes à leurs organisations respectives — créant de la confusion lorsque les priorités entrent en concurrence.` },
    polarity: -1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 5, 'TRT_CI': 2, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 3, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S11aD',
    questionId: 'Q11a',
    text: { en: `The senior team functions more as a collection of functional heads advocating for their own areas than as an integrated team making collective decisions.`, fr: `L'équipe dirigeante fonctionne davantage comme un ensemble de responsables fonctionnels défendant leurs propres domaines que comme une équipe intégrée prenant des décisions collectives.` },
    polarity: -1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 4, 'TRT_CI': 4, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 2, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S11aE',
    questionId: 'Q11a',
    text: { en: `The senior team has a shared language and frameworks for discussing strategy — they can debate constructively without it becoming positional.`, fr: `L'équipe dirigeante dispose d'un langage commun et de cadres partagés pour discuter de la stratégie — elle peut débattre de manière constructive sans que cela devienne positionnel.` },
    polarity: 1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 3, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 4, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 3 } as Record<TraitId, number>,
   },
  ],
 },
 {
  id: 'Q11b',
  dimensionId: 'D6' as DimensionId,
  text: { en: `Now thinking about the NEXT layer of leadership (directors, senior managers, department heads below the senior team) — how well does alignment cascade from the top?`, fr: `En pensant maintenant au NIVEAU SUIVANT de leadership (directeurs, managers seniors, chefs de département) — dans quelle mesure l'alignement se transmet-il depuis le sommet ?` },
  contextPrompt: { en: `Think of a strategic commitment made by the senior team. Did it translate consistently into action at the next layer? If not, where did it break down?`, fr: `Pensez à un engagement stratégique de l'équipe dirigeante. S'est-il traduit en actions au niveau suivant ? Sinon, où cela a-t-il échoué ?` },
  statements: [
   {
    id: 'S11bA',
    questionId: 'Q11b',
    text: { en: `The senior team is aligned, but this alignment does not reliably translate into consistent action at the next leadership layer — commitments soften as they cascade.`, fr: `L'équipe dirigeante est alignée, mais cet alignement ne se traduit pas de manière fiable en actions cohérentes au niveau de leadership suivant — les engagements s'atténuent en cascadant.` },
    polarity: -1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 4, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 3, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 3, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S11bB',
    questionId: 'Q11b',
    text: { en: `The next layer of leaders understands and actively supports the strategic direction — they translate it into their own context and drive it through their teams.`, fr: `Le niveau de leadership suivant comprend et soutient activement la direction stratégique — ils la traduisent dans leur propre contexte et la portent à travers leurs équipes.` },
    polarity: 1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 3, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 3, 'TRT_CO': 4, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S11bC',
    questionId: 'Q11b',
    text: { en: `Some leaders at the next layer are visibly resistant or sceptical — they comply with directives but do not actively drive the strategy.`, fr: `Certains leaders au niveau suivant sont visiblement résistants ou sceptiques — ils se conforment aux directives mais ne portent pas activement la stratégie.` },
    polarity: -1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 3, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 2, 'TRT_CO': 5, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S11bD',
    questionId: 'Q11b',
    text: { en: `The next layer was not meaningfully involved in shaping the strategy — they received it rather than co-created it, and this shows in their commitment level.`, fr: `Le niveau suivant n'a pas été impliqué de manière significative dans l'élaboration de la stratégie — ils l'ont reçue plutôt que cocréée, et cela se voit dans leur niveau d'engagement.` },
    polarity: -1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 2, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 2, 'TRT_DC': 0, 'TRT_LI': 2, 'TRT_CO': 4, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S11bE',
    questionId: 'Q11b',
    text: { en: `Senior leaders have invested in helping the next layer understand the strategy's implications for their specific area — not just broadcasting the message.`, fr: `Les dirigeants seniors ont investi pour aider le niveau suivant à comprendre les implications de la stratégie pour leur domaine spécifique — pas seulement diffuser le message.` },
    polarity: 1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 3, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 4, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 3, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
  ],
 },
 {
  id: 'Q12',
  dimensionId: 'D6' as DimensionId,
  text: { en: `How strong is the leadership team's collective ability to read execution challenges accurately and choose the right interventions?`, fr: `Quelle est la capacité collective de l'équipe de leadership à lire avec justesse les défis d'exécution et à choisir les bonnes interventions ?` },
  contextPrompt: { en: `Think of a recent execution problem. How was it diagnosed? Did the chosen intervention address the root cause, or did it treat a symptom?`, fr: `Pensez à un problème d'exécution récent. Comment a-t-il été diagnostiqué ? L'intervention choisie a-t-elle traité la cause racine ou un symptôme ?` },
  statements: [
   {
    id: 'S12A',
    questionId: 'Q12',
    text: { en: `When execution runs into trouble, the default response tends to be 'communicate more' or 'try harder' — there is limited ability to distinguish whether the real issue is structural, capability-related, motivational, or something else.`, fr: `Quand l'exécution rencontre des difficultés, la réponse par défaut tend à être « communiquons plus » ou « essayons plus fort » — la capacité à distinguer reste faible si le vrai problème est structurel, lié aux compétences, motivationnel, ou autre.` },
    polarity: -1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 2, 'TRT_II': 0, 'TRT_DC': 6, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 2 } as Record<TraitId, number>,
   },
   {
    id: 'S12B',
    questionId: 'Q12',
    text: { en: `Leaders tend to apply the same management approach regardless of the situation — there is little adaptation of style or intervention type based on the specific nature of the problem.`, fr: `Les dirigeants ont tendance à appliquer la même approche managériale quelle que soit la situation — l'adaptation reste limitée du style ou du type d'intervention en fonction de la nature spécifique du problème.` },
    polarity: -1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 3, 'TRT_II': 0, 'TRT_DC': 5, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 2 } as Record<TraitId, number>,
   },
   {
    id: 'S12C',
    questionId: 'Q12',
    text: { en: `The leadership team has a track record of accurately diagnosing execution problems and matching the right intervention to the right root cause — including knowing when to leave things alone.`, fr: `L'équipe de leadership a un historique de diagnostic précis des problèmes d'exécution et de correspondance entre la bonne intervention et la bonne cause racine — y compris savoir quand ne rien faire.` },
    polarity: 1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 3, 'TRT_II': 0, 'TRT_DC': 5, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 2 } as Record<TraitId, number>,
   },
   {
    id: 'S12D',
    questionId: 'Q12',
    text: { en: `Leaders are strong at diagnosing issues within their own function but struggle to read cross-functional or systemic problems — they tend to see the piece of the elephant closest to them.`, fr: `Les dirigeants sont forts pour diagnostiquer les problèmes au sein de leur propre fonction mais peinent à lire les problèmes transversaux ou systémiques — ils ont tendance à voir la partie de l'éléphant la plus proche d'eux.` },
    polarity: -1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 4, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 4, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 2 } as Record<TraitId, number>,
   },
   {
    id: 'S12E',
    questionId: 'Q12',
    text: { en: `When feedback surfaces about execution difficulties, leaders sometimes react defensively or dismiss the signal rather than treating it as diagnostic information.`, fr: `Quand des retours remontent sur des difficultés d'exécution, les dirigeants réagissent parfois défensivement ou rejettent le signal plutôt que de le traiter comme une information diagnostique.` },
    polarity: -1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 3, 'TRT_DC': 4, 'TRT_LI': 0, 'TRT_CO': 3, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
  ],
 },
 {
  id: 'Q13',
  dimensionId: 'D6' as DimensionId,
  text: { en: `Do the leaders who will drive deployment have the credibility, relational trust, and influence needed to mobilise action across teams and stakeholders?`, fr: `Les leaders qui piloteront le déploiement ont-ils la crédibilité, la confiance relationnelle et l'influence nécessaires pour mobiliser l'action ?` },
  contextPrompt: { en: `Think of a leader in a critical deployment role. If they asked another team to reprioritise their work, would that team do it willingly — or would it require escalation?`, fr: `Pensez à un leader dans un rôle critique. S'il demandait à une autre équipe de reprioriser, le ferait-elle volontairement — ou faudrait-il escalader ?` },
  statements: [
   {
    id: 'S13A',
    questionId: 'Q13',
    text: { en: `Some of the leaders who hold critical deployment roles have positional authority but lack the informal influence to get people to go beyond compliance.`, fr: `Certains dirigeants occupant des rôles critiques de déploiement ont l'autorité hiérarchique mais manquent de l'influence informelle pour amener les équipes à aller au-delà de la simple conformité.` },
    polarity: -1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 6, 'TRT_CO': 2, 'TRT_CF': 2 } as Record<TraitId, number>,
   },
   {
    id: 'S13B',
    questionId: 'Q13',
    text: { en: `The leaders driving deployment have strong, trust-based relationships across the organisation — people are willing to go the extra mile because they believe in and respect these leaders personally.`, fr: `Les dirigeants portant le déploiement ont des relations solides fondées sur la confiance à travers l'organisation — les collaborateurs sont prêts à s'engager au-delà du strict nécessaire parce qu'ils croient en ces dirigeants et les respectent personnellement.` },
    polarity: 1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 2, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 5, 'TRT_CO': 3, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S13C',
    questionId: 'Q13',
    text: { en: `Leaders' credibility and influence is concentrated within their own function — when they need to mobilise action in other parts of the organisation, they struggle to gain traction without escalating.`, fr: `La crédibilité et l'influence des dirigeants sont concentrées au sein de leur propre fonction — quand ils doivent mobiliser l'action dans d'autres parties de l'organisation, ils peinent à gagner en traction sans escalader.` },
    polarity: -1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 4, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 4, 'TRT_CO': 0, 'TRT_CF': 2 } as Record<TraitId, number>,
   },
   {
    id: 'S13D',
    questionId: 'Q13',
    text: { en: `There are specific leaders whose personal credibility is so strong that their involvement in an initiative significantly increases the likelihood of cross-functional cooperation.`, fr: `Certains dirigeants possèdent la crédibilité personnelle est si forte que leur implication dans une initiative accroît considérablement la probabilité de coopération transversale.` },
    polarity: 1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 3, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 5, 'TRT_CO': 2, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S13E',
    questionId: 'Q13',
    text: { en: `Some leaders have accumulated political capital but not trust-based capital — they can get compliance through transactional relationships, but cannot generate genuine commitment.`, fr: `Certains dirigeants ont accumulé du capital politique mais pas du capital de confiance — ils peuvent obtenir la conformité par des relations transactionnelles, mais ne peuvent pas générer un engagement véritable.` },
    polarity: -1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 2, 'TRT_DC': 0, 'TRT_LI': 4, 'TRT_CO': 4, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
  ],
 },
 {
  id: 'Q14',
  dimensionId: 'D6' as DimensionId,
  text: { en: `Do the leaders responsible for executing the strategy have the specific experience, skills, and domain knowledge this particular strategy demands?`, fr: `Les leaders responsables de l'exécution possèdent-ils l'expérience spécifique, les compétences et l'expertise que cette stratégie exige ?` },
  contextPrompt: { en: `What is the single biggest execution challenge the new strategy presents? Which leader owns it, and have they done something like this before?`, fr: `Quel est le plus grand défi d'exécution de la nouvelle stratégie ? Quel leader en est responsable, et a-t-il déjà fait quelque chose de similaire ?` },
  statements: [
   {
    id: 'S14A',
    questionId: 'Q14',
    text: { en: `The leadership team is strong in managing the current business, but the new strategy asks them to do things fundamentally different from their past experience — and these gaps have not been explicitly mapped.`, fr: `L'équipe de leadership est forte dans la gestion de l'activité courante, mais la nouvelle stratégie leur demande de faire des choses fondamentalement différentes de leur expérience passée — et ces écarts n'ont pas été explicitement cartographiés.` },
    polarity: -1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 2, 'TRT_II': 0, 'TRT_DC': 2, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 6 } as Record<TraitId, number>,
   },
   {
    id: 'S14B',
    questionId: 'Q14',
    text: { en: `Some leaders bring directly relevant experience from previous roles or organisations that will be valuable for the specific demands of the new strategy.`, fr: `Certains dirigeants apportent une expérience directement pertinente de rôles ou d'organisations précédents qui sera précieuse pour les exigences spécifiques de la nouvelle stratégie.` },
    polarity: 1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 2, 'TRT_LI': 2, 'TRT_CO': 0, 'TRT_CF': 6 } as Record<TraitId, number>,
   },
   {
    id: 'S14C',
    questionId: 'Q14',
    text: { en: `Where leadership skill gaps exist, the organisation has identified them and has plans in place — whether through targeted development, coaching, advisory support, or recruitment.`, fr: `Là où des lacunes de compétences du leadership existent, l'organisation les a identifiées et a des plans en place — que ce soit par le développement ciblé, le coaching, le soutien consultatif ou le recrutement.` },
    polarity: 1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 3, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 3, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 4 } as Record<TraitId, number>,
   },
   {
    id: 'S14D',
    questionId: 'Q14',
    text: { en: `The leadership team has been assembled primarily based on functional expertise and tenure rather than on fitness for the specific execution challenges the new strategy presents.`, fr: `L'équipe de leadership a été constituée principalement sur la base de l'expertise fonctionnelle et de l'ancienneté plutôt que sur l'adéquation avec les défis d'exécution spécifiques que la nouvelle stratégie présente.` },
    polarity: -1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 3, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 2, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 5 } as Record<TraitId, number>,
   },
   {
    id: 'S14E',
    questionId: 'Q14',
    text: { en: `Leaders who have successfully led similar transformations or strategic shifts before are available to coach or support those facing this type of challenge for the first time.`, fr: `Des dirigeants ayant mené avec succès des transformations ou des changements stratégiques similaires sont disponibles pour coacher ou soutenir ceux qui font face à ce type de défi pour la première fois.` },
    polarity: 1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 3, 'TRT_LI': 3, 'TRT_CO': 0, 'TRT_CF': 4 } as Record<TraitId, number>,
   },
  ],
 },
 {
  id: 'Q15',
  dimensionId: 'D7' as DimensionId,
  text: { en: `How well does the organisation translate strategic intent into language that enables people at every level to understand what it means for their own work?`, fr: `Dans quelle mesure l'organisation traduit-elle l'intention stratégique en un langage permettant aux personnes à chaque niveau de comprendre ce que cela signifie pour leur travail ?` },
  contextPrompt: { en: `Pick someone two levels below the senior team. If you asked them to explain what the strategy means for their daily work, how confident are you they could?`, fr: `Choisissez quelqu'un deux niveaux au-dessous du comité de direction. S'il devait expliquer ce que la stratégie signifie pour son travail quotidien, le pourrait-il ?` },
  statements: [
   {
    id: 'S15A',
    questionId: 'Q15',
    text: { en: `The strategy has been presented at town halls or in documents, but most people below the senior team would struggle to explain what specifically needs to change in their own work.`, fr: `La stratégie a été présentée lors de town halls ou dans des documents, mais la plupart des personnes au-dessous du comité de direction auraient du mal à expliquer ce qui doit spécifiquement changer dans leur propre travail.` },
    polarity: -1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 3, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 4, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 3, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S15B',
    questionId: 'Q15',
    text: { en: `Translation of the strategy into local context depends entirely on individual managers — some teams have a rich understanding while others have received only generic messaging.`, fr: `La traduction de la stratégie en contexte local dépend entièrement des managers individuels — certaines équipes ont une compréhension riche tandis que d'autres n'ont reçu qu'un message générique.` },
    polarity: -1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 4, 'TRT_DC': 0, 'TRT_LI': 3, 'TRT_CO': 3, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S15C',
    questionId: 'Q15',
    text: { en: `People understand the headline direction, but the practical implications — which projects to prioritise, which trade-offs to make, which legacy activities to stop — have not been made explicit.`, fr: `Les collaborateurs comprennent la direction principale, mais les implications pratiques — quels projets prioriser, quels arbitrages faire, quelles activités héritées arrêter — n'ont pas été rendues explicites.` },
    polarity: -1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 3, 'TRT_CI': 0, 'TRT_ED': 3, 'TRT_AC': 0, 'TRT_II': 4, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S15D',
    questionId: 'Q15',
    text: { en: `The organisation has invested in translating the strategy into function-specific and level-specific language, so that people can see what it means for their daily priorities and decisions.`, fr: `L'organisation a investi dans la traduction de la stratégie en langage spécifique par fonction et par niveau, pour que chaque collaborateur puisse voir ce que cela signifie pour leurs priorités et décisions quotidiennes.` },
    polarity: 1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 3, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 4, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 3, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S15E',
    questionId: 'Q15',
    text: { en: `There is a risk that the strategic narrative sounds inspiring at the top level but becomes disconnected from operational reality as it moves through the organisation.`, fr: `Le récit stratégique risque d'être inspirant au sommet mais de se déconnecter de la réalité opérationnelle à mesure qu'il traverse l'organisation.` },
    polarity: -1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 3, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 4, 'TRT_DC': 3, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
  ],
 },
 {
  id: 'Q16',
  dimensionId: 'D7' as DimensionId,
  text: { en: `How freely and reliably does critical information flow upward to leaders and laterally across teams?`, fr: `L'information critique circule-t-elle librement et de manière fiable vers les dirigeants et latéralement entre équipes ?` },
  contextPrompt: { en: `When was the last time a leader learned about a problem significantly later than the working-level team knew about it? What caused the delay?`, fr: `Quand un leader a-t-il appris un problème significativement plus tard que l'équipe opérationnelle ? Qu'est-ce qui a causé le délai ?` },
  statements: [
   {
    id: 'S16A',
    questionId: 'Q16',
    text: { en: `Leaders are often the last to know about execution risks or customer concerns — by the time information reaches them, it has been filtered, delayed, or reframed to sound less alarming.`, fr: `Les dirigeants sont souvent les derniers informés des risques d'exécution ou des préoccupations clients — le temps que l'information leur parvienne, elle a été filtrée, retardée ou reformulée pour paraître moins alarmante.` },
    polarity: -1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 2, 'TRT_II': 6, 'TRT_DC': 2, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S16B',
    questionId: 'Q16',
    text: { en: `Information flows relatively well within functions (vertically), but poorly across functions (laterally) — teams working on related objectives often don't know what the other is doing.`, fr: `L'information circule relativement bien au sein des fonctions (verticalement), mais mal entre les fonctions (latéralement) — des équipes travaillant sur des objectifs liés ne savent souvent pas ce que l'autre fait.` },
    polarity: -1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 4, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 4, 'TRT_DC': 2, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S16C',
    questionId: 'Q16',
    text: { en: `There are formal channels for upward communication, but people do not trust them to carry uncomfortable truths — the real conversations happen informally or not at all.`, fr: `Il existe des canaux formels de communication ascendante, mais les collaborateurs ne leur font pas confiance pour porter des vérités inconfortables — les vraies conversations se passent informellement ou pas du tout.` },
    polarity: -1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 4, 'TRT_DC': 0, 'TRT_LI': 3, 'TRT_CO': 3, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S16D',
    questionId: 'Q16',
    text: { en: `Leaders actively seek out unfiltered information — they go to where the work happens, ask direct questions, and have created an environment where people can share the unvarnished reality.`, fr: `Les dirigeants recherchent activement l'information non filtrée — ils se rendent là où le travail se fait, posent des questions directes, et ont créé un environnement où les collaborateurs peuvent partager la réalité brute.` },
    polarity: 1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 4, 'TRT_DC': 3, 'TRT_LI': 0, 'TRT_CO': 3, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S16E',
    questionId: 'Q16',
    text: { en: `The organisation generates a lot of data and reporting, but it does not translate into genuine insight for decision-makers — there is information overload without information quality.`, fr: `L'organisation génère beaucoup de données et de rapports, mais cela ne se traduit pas en véritable compréhension pour les décideurs — la surcharge d'information noie la qualité.` },
    polarity: -1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 2, 'TRT_AC': 0, 'TRT_II': 5, 'TRT_DC': 3, 'TRT_LI': 0, 'TRT_CO': 0, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
  ],
 },
 {
  id: 'Q17',
  dimensionId: 'D8' as DimensionId,
  text: { en: `To what extent have the people who will carry the weight of deployment been meaningfully involved in shaping the execution approach?`, fr: `Dans quelle mesure les personnes qui porteront le poids du déploiement ont-elles été véritablement impliquées dans la conception de l'approche d'exécution ?` },
  contextPrompt: { en: `How were middle managers involved in designing the execution approach? Were they consulted, co-creators, or recipients?`, fr: `Comment l'encadrement intermédiaire ont-ils été impliqués dans l'approche d'exécution ? Consultés, cocréateurs ou simples destinataires ?` },
  statements: [
   {
    id: 'S17A',
    questionId: 'Q17',
    text: { en: `The deployment plan has been designed by a small group at the top — the people who will carry the weight of execution have received it rather than shaped it.`, fr: `Le plan de déploiement a été conçu par un petit groupe au sommet — les personnes qui porteront le poids de l'exécution l'ont reçu plutôt que façonné.` },
    polarity: -1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 2, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 2, 'TRT_CO': 6, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S17B',
    questionId: 'Q17',
    text: { en: `Middle managers were consulted during the planning phase, and some of their input was incorporated — but many feel their involvement was more about being informed than being genuinely listened to.`, fr: `Les cadres intermédiaires ont été consultés pendant la phase de planification, et certaines de leurs contributions ont été intégrées — mais beaucoup estiment que leur implication relevait davantage de l'information que de l'écoute véritable.` },
    polarity: -1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 3, 'TRT_DC': 0, 'TRT_LI': 2, 'TRT_CO': 5, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S17C',
    questionId: 'Q17',
    text: { en: `Key delivery leads and middle managers have been actively involved in designing how the strategy will be executed — they see their fingerprints on the plan and feel personal accountability for its success.`, fr: `Les responsables de livraison clés et les cadres intermédiaires ont été activement impliqués dans la conception de la façon dont la stratégie sera exécutée — ils voient leur empreinte sur le plan et ressentent une responsabilité personnelle envers son succès.` },
    polarity: 1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 2, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 3, 'TRT_CO': 5, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S17D',
    questionId: 'Q17',
    text: { en: `There is visible energy and initiative-taking among the people who will lead deployment — they are volunteering for roles, proposing ideas, and pulling the work forward rather than waiting to be directed.`, fr: `Il y a une énergie visible et de la prise d'initiative parmi les personnes qui dirigeront le déploiement — ils se portent volontaires pour des rôles, proposent des idées, et tirent le travail vers l'avant plutôt que d'attendre qu'on les dirige.` },
    polarity: 1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 2, 'TRT_CO': 5, 'TRT_CF': 3 } as Record<TraitId, number>,
   },
   {
    id: 'S17E',
    questionId: 'Q17',
    text: { en: `Some of the most capable middle managers are sceptical about the execution approach — not because they disagree with the strategy, but because they have seen previous deployment efforts fail.`, fr: `Certains des cadres intermédiaires les plus compétents sont sceptiques quant à l'approche d'exécution — non pas parce qu'ils sont en désaccord avec la stratégie, mais parce qu'ils ont vu des déploiements précédents échouer.` },
    polarity: -1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 3, 'TRT_II': 3, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 4, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
  ],
 },
 {
  id: 'Q18',
  dimensionId: 'D8' as DimensionId,
  text: { en: `How well do current incentive structures actually reinforce the behaviours and outcomes the new strategy requires?`, fr: `Dans quelle mesure les structures d'incitation actuelles renforcent-elles les comportements et résultats que la nouvelle stratégie exige ?` },
  contextPrompt: { en: `What gets rewarded in practice — individual functional performance, or cross-functional contribution to strategic outcomes? Give an example of a recent promotion or recognition decision.`, fr: `Qu'est-ce qui est récompensé en pratique — la performance fonctionnelle individuelle ou la contribution transversale aux résultats stratégiques ? Donnez un exemple récent.` },
  statements: [
   {
    id: 'S18A',
    questionId: 'Q18',
    text: { en: `People are still evaluated and rewarded based on criteria that reflect the previous strategy — there has been no visible change to performance metrics, bonus structures, or promotion criteria.`, fr: `Les collaborateurs sont toujours évalués et récompensés sur la base de critères qui reflètent la stratégie précédente — il n'y a eu aucun changement visible des indicateurs de performance, des structures de bonus ou des critères de promotion.` },
    polarity: -1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 5, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 3, 'TRT_CF': 2 } as Record<TraitId, number>,
   },
   {
    id: 'S18B',
    questionId: 'Q18',
    text: { en: `The incentive system rewards individual functional performance, which will make it difficult to motivate the cross-functional collaboration and shared outcomes the strategy demands.`, fr: `Le système d'incitation récompense la performance fonctionnelle individuelle, ce qui rendra difficile la motivation pour la collaboration transversale et les résultats communs que la stratégie exige.` },
    polarity: -1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 4, 'TRT_CI': 4, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 2, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
   {
    id: 'S18C',
    questionId: 'Q18',
    text: { en: `Recognition and rewards are informal and manager-dependent — whether someone is recognised for strategic contribution depends on who their manager is rather than on a consistent practice.`, fr: `La reconnaissance et les récompenses sont informelles et dépendent du manager — qu'une personne soit reconnue pour sa contribution stratégique dépend de qui est son manager plutôt que d'une pratique cohérente.` },
    polarity: -1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 3, 'TRT_SA': 0, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 4, 'TRT_CF': 3 } as Record<TraitId, number>,
   },
   {
    id: 'S18D',
    questionId: 'Q18',
    text: { en: `The organisation has reviewed its incentive structures in light of the new strategy and has made deliberate changes to ensure people are rewarded for the behaviours and outcomes that matter most.`, fr: `L'organisation a revu ses structures d'incitation à la lumière de la nouvelle stratégie et a apporté des changements délibérés pour s'assurer que les collaborateurs sont récompensés pour les comportements et résultats qui comptent le plus.` },
    polarity: 1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 4, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 0, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 3, 'TRT_CF': 3 } as Record<TraitId, number>,
   },
   {
    id: 'S18E',
    questionId: 'Q18',
    text: { en: `There is a disconnect between what leaders say matters and what actually gets rewarded — the strategy talks about collaboration, speed, and customer focus, but promotions still go to people who protect their turf.`, fr: `Il y a un décalage entre ce que les dirigeants disent être important et ce qui est réellement récompensé — la stratégie parle de collaboration, de rapidité et d'orientation client, mais les promotions vont toujours à ceux qui protègent leur territoire.` },
    polarity: -1 as 1 | -1,
    tag: '—' as DesignAdoptionTag,
    traitAllocations: { 'TRT_CA': 0, 'TRT_SA': 4, 'TRT_CI': 0, 'TRT_ED': 0, 'TRT_AC': 0, 'TRT_II': 3, 'TRT_DC': 0, 'TRT_LI': 0, 'TRT_CO': 3, 'TRT_CF': 0 } as Record<TraitId, number>,
   },
  ],
 },
]
